#+TITLE: Climate Change Explorations
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt,a4paper,titlepage]
#+LATEX_HEADER: \def\today{\number\day\space\ifcase\month\or January\or February\or March\or April\or May\or June\or July\or August\or September\or October\or November\or December\fi \space \number\year}
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage{amssymb,amsmath}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage[round]{natbib}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \usepackage[squaren,cdot]{SIunits}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER: \newcommand{\isotope}[2]{\ensuremath{{^{#1}\mathrm{#2}}}}
#+LATEX_HEADER: \lhead{}
#+LATEX_HEADER: \rhead{}
#+LATEX_HEADER: \lfoot{Climate Change}
#+LATEX_HEADER: \cfoot{\thepage}
#+LATEX_HEADER: \rfoot{\thedate}
#+LATEX_HEADER_EXTRA: \author{Stefan Revets}
#+LATEX_HEADER_EXTRA: \pretitle{\flushleft\LARGE\bfseries\vskip 80mm}
#+LATEX_HEADER_EXTRA: \posttitle{\par}
#+LATEX_HEADER_EXTRA: \preauthor{\flushleft}
#+LATEX_HEADER_EXTRA: \postauthor{\par}
#+LATEX_HEADER_EXTRA: \predate{\flushleft}
#+LATEX_HEADER_EXTRA: \postdate{\par{In Progress}}
#+OPTIONS: ^:{}

* Introduction
In one of our monthly discussions, Birger asked if there was a proper
understanding of the processes and mechanisms driving climate change
(on a geological timescale). The glacial-interglacial alternations
have been documented to go back some considerable time, and
Milankovitch cycles are usually put forward as explanation. My
impression is that we don't really understand what is going on, but it
seemed only fair to look a little closer into what has been proposed
over the years.

A considerable amount of work has been expended already, using the
Milankovitch cycles as a basis \citep{milankovitch20:theorie},
refining and expanding the processes involved (changes in albedo,
moisture content in the atmosphere, ocean circulation, and so on and
so forth).

Different approaches are few and far in between. A distinct
alternative proposes that the cycles may be endogenous, i.e., the
consequence of behaviour of coupled differential equations describing
the processes of heat transfer in the Earth's system, decoupled and
independent from astronomical driving or forcing
\citep{maslov14:self-organisation}.

Looking at the Oxygen isotope curves from the Greenland and Deuterium
from Antarctic ice cores more closely prompts a whole series of
questions. Why is it that a great many (most?) warming events are
short and abrupt and followed by a much more gradual, lower, cooling
sequence? What happened after the last glacial to bring about an
apparently unprecedented 10 kY of stable climate? The Greenland and
Antarctica isotope curves and CO_{2} curves appear to be quite
similar, but which one changes first? That is, in the (pre-human
intervention) past, are the changing CO_{2} concentrations a cause or
an effect of the temperature changes? What is the role of CO_{2} in
the Dansgaard-Oescher cycles; an enabler, a moderator, an accelerator?
How come that the there is no discernable insolation change comparable
to the Dansgaard-Oescher cycle time intervals?

The curves do show similarities to curves of limit cycles, `chaotic'
systems, or strange attractor systems. It was rather nice then, to
come across a paper \citep{steffen-al18:trajectories} that sketches
this possible mechanism. Another intrigueing discussion was presented
by \citet{baez12:twf319}, and then there is the endogenous,
Lotka-Volterra like modelling as well
\citep{maslov14:self-organisation}.

In order to try and get a better understanding of the whole thing,
taking a step back from all that engrossing, immediate detail, and
going back to first principles seems like a good plan.

At the most fundamental level, the Earth behaves like a heat engine,
powered by the Sun.  The Earth, atmosphere, oceans and land mass,
absorb and emit energy, all of which comes from the Sun. As the Earth
turns around its own axis, around the Sun, rotating on its titled,
wobbling axis, the amount of energy coming down and hence available
for reflection, absorption and emission changes at a wide variety of
time scales. Some of that solar energy is variously trapped by water
vapour, CO_{2} and CH_{4} in the atmosphere, as well as by the oceans
and the continents, and downgraded to heat in the process. Part of
that heat is then radiated out again into space, so that temperature
on Earth remains within limits. There is of course the additional
redistribution across the Earth of the absorbed heat, adding
substantial complexity to the entire process.

\citet{milankovitch20:theorie} used the Stockwell-Pilgrim values for
eccentricity, obliquity and precession to calculate the incoming solar
radiation for latitudes \unit{55}{\degree}, \unit{60}{\degree} and
\unit{65}{\degree} N for the last 500,000 years.

Since that time, the calculation of orbital parameters have continued
to improve \citep{laskar-al04:insolation,laskar-al11:la2010}, and,
more importantly, we now have access to much more precisely dated
palaeotemperatures, in particular temperature data from Greenland and
Antarctica ice cores. In addition, we also have CO_{2} and CH_{4}
measurements from those same ice cores. And so we have everything we
need to (re)calculate the amount of solar energy delivered anywhere on
the Earth and revisit any relations with the temperature changes
recorded in the ice cores.

* Data Sources
** Astronomical Data
Laskar and colleagues have created a website to allow on-line
calculation of insolation given a set of input parameters using the
results published in \citet{laskar-al04:insolation}
(http://vo.imcce.fr/insola/earth/online/earth/online/index.php).

This provides an easy means of getting the data needed here.

A useful measure would be the mean daily insolation. This can be
converted for calculation purposes into a mean longitude as set out in
the table below

| Date         | Mean Longitude | Season   |
|--------------+----------------+----------|
| 21 March     |              0 | equinox  |
| 21 April     |             30 |          |
| 21 May       |             60 |          |
| 21 June      |             90 | solstice |
| 21 July      |            120 |          |
| 21 August    |            150 |          |
| 21 September |            180 | equinox  |
| 21 October   |            210 |          |
| 21 November  |            240 |          |
| 21 December  |            270 | solstice |
| 21 January   |            300 |          |
| 21 February  |            330 |          |

Note that intermediate values can be used if desired.

Other assumptions and setting include the following
- time :: is expressed in Julian years, with a starting/ending point
          of J2000.0.
- solar constant :: \unit{1368}{\watt\per\squaremetre}
- latitudes :: positive for N, negative for S hemisphere
- insolation :: expressed in \watt\per\squaremetre

Let's generate mean daily insolation data for the 4 season onsets over
100 year intervals for the last 1 million years and that at 4
latitudes, and use a naming convention for the data files

| latitude             | name      |
|----------------------+-----------|
| \unit{0}{\degree}    | insol_equ |
| \unit{25}{\degree}   | insol_tro |
| \unit{50}{\degree}   | insol_tem |
| \unit{72.5}{\degree} | insol_pol |

The latitude chosen for the polar region is that of the location of
the GRIP core in Greenland.  Of course, there will be only zeroes for
the winter solstice for the polar latitude. Each of the data files is
made up of the time (expressed in units of thousands of Julian Years,
and negative as we're interested in values before the present) and the
calculated insolation (in \watt\per\squaremetre).

** Temperature Data
GRIP and GISP Oxygen isotope data and Vostok Deuterium data obtained
from the National Snow and Ice Data Center, University of Colorado at
Boulder, and the WDC-A for Paleoclimatology, National Geophysical Data
Center, Boulder, Colorado.

** Atmospheric gases
I still need to track down ice-based CO_{2} and CH_{4} data, ideally
both from Greenland and from Antarctic ice cores. It is important in
that the measurements of these gases also has isotope measurements in
the same samples: interpolation would dilute the reliability of the
data for study and analysis.

** Heat capture
I need to track down the absorption spectrum of CO_{2} and H_{2}O, as
well as the means to calculate the relation between concentration and
amount of heat converted/trapped by these gases from the (incoming)
solar radiation and outgoing radiation.

* Calculations
:PROPERTIES:
:session: *R*
:cache: yes
:results: output graphics
:exports: both
:END:

#+BEGIN_SRC R :results none
  library("dplyr")
  library("ggplot2")
  library("magrittr")
  library("pracma")
  library("tidyr")

  R_gas <- 8.314471               # J / K mol, Gas constant
  N_A <- 6.02214129e23            # / mol, Avogadro constant
  k_boltzmann <- 1.3806488e-23    # J / K, Boltzmann constant (R / N_A)
  h_planck <- 6.62606957e-34      # J s, Planck constant
  c_light <- 299792458            # m / s, speed of light
  sigma_stefan <- 5.670373e-8     # W / m^2 K^4, Stefan-Boltzmann constant
  p0 <- 101325                    # Pa, standard pressure
#+END_SRC
The various constants listed here have been taken from CODATA 2010.

** Data preparation
First of all, let's bring in the insolation data and combine the data
so that we end up with separate data frames for each of the latitudes,
but bringing each of the dates together.

First bring in the data for the equator. In the process, let's change
the time into actual years, and drop the negative. That way, it will
be compatible with the ice core data
#+BEGIN_SRC R :results none
  insol_equ <- read.table("data/insol_equ_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_equ_90.dat",
                           col.names = c('time','june'))
  insol_equ %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_equ_180.dat",
                           col.names = c('time','september'))
  insol_equ %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_equ_270.dat",
                           col.names = c('time','december'))
  insol_equ %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

Now repeat for the other latitudes; first for the tropic of cancer
#+BEGIN_SRC R :results none
  insol_tro <- read.table("data/insol_tro_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_tro_90.dat",
                           col.names = c('time','june'))
  insol_tro %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tro_180.dat",
                           col.names = c('time','september'))
  insol_tro %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tro_270.dat",
                           col.names = c('time','december'))
  insol_tro %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

then for the temperate zone
#+BEGIN_SRC R :results none
  insol_tem <- read.table("data/insol_tem_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_tem_90.dat",
                           col.names = c('time','june'))
  insol_tem %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tem_180.dat",
                           col.names = c('time','september'))
  insol_tem %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tem_270.dat",
                           col.names = c('time','december'))
  insol_tem %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

and finally for the polar region
#+BEGIN_SRC R :results none
  insol_pol <- read.table("data/insol_pol_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_pol_90.dat",
                           col.names = c('time','june'))
  insol_pol %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_pol_180.dat",
                           col.names = c('time','september'))
  insol_pol %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

Now let's get the GRIP and GISP oxygen isotope data as well as the
deuterium data from the Vostok core
#+BEGIN_SRC R :results none
  grip <- read.table("grip/gripd18O.dat",
                     col.names = c('depth','time','del18O'))
  gisp <- read.table("gisp/gispd18O.dat",
                     col.names = c('depth','time','del18O'))
  vostok <-  read.table("vostok/vostok_d.dat",
                        col.names = c('depth', 'time', 'deuterium', 'deltaTS'))
#+END_SRC

** Exploration
*** Insolation
First, let's look at the results of the astronomical calculations
#+BEGIN_SRC R :file output/insol_overview.pdf
  insolation <- insol_pol %>%
      gather("season","power", 2:4) %>%
      mutate(latitude = "Polar") %>%
      bind_rows(gather(insol_tem, "season", "power", 2:5) %>%
                mutate(latitude = "Temperate")) %>%
      bind_rows(gather(insol_tro, "season", "power", 2:5) %>%
                mutate(latitude = "Tropical")) %>%
      bind_rows(gather(insol_equ, "season", "power", 2:5) %>%
                mutate(latitude = "Equatorial"))

  ggplot(insolation) +
      geom_line(aes(time, power, colour = season)) +
      labs(title = "Overview of seasonal insolation at key latitudes",
           x = "Time (Years)",
           y = "Insolation (W/m2)") +
      facet_wrap(~latitude) +
      theme(legend.position = "bottom")
#+END_SRC

Let's see if anything can be gleaned from these values. One obvious
avenue to pursue is to see how the summer-winter differences evolve?
#+BEGIN_SRC R :file output/insol_delta.pdf
  insol_del <- insol_equ %>%
      mutate(deficit = june - december,
             latitude = "Equatorial") %>%
      bind_rows(insol_tro %>%
                mutate(deficit = june - december,
                       latitude = "Tropical")) %>%
      bind_rows(insol_tem %>%
                mutate(deficit = june - december,
                       latitude = "Temperate")) %>%
      select(-march, -june, -september, -december)

  ggplot(insol_del) +
      geom_line(aes(time, deficit, color = latitude)) +
      labs(title = "Summer-Winter Insolation Deficit",
           x = "Time (Years)",
           y = "Insolation Deficit (W/m2)") +
      theme(legend.position = "bottom")
#+END_SRC

Are there any differences relative to the mean insolations for each
latitude, or are these essentially the same? 

#+BEGIN_SRC R :file output/insol_rel.pdf
  insol_means_pol <- summarise_each(insol_pol, funs(mean))
  insol_means_tem <- summarise_each(insol_tem, funs(mean))
  insol_means_tro <- summarise_each(insol_tro, funs(mean))
  insol_means_equ <- summarise_each(insol_equ, funs(mean))

  insol_rel <- insol_equ %>%
      mutate(deficit = december * insol_means_equ$june /
                 (june * insol_means_equ$december),
             latitude = "Equatorial") %>%
      bind_rows(insol_tro %>%
                mutate(deficit = december * insol_means_tro$june/
                           (june * insol_means_tro$december),
                       latitude = "Tropical")) %>%
      bind_rows(insol_tem %>%
                mutate(deficit = december * insol_means_tem$june/
                           (june * insol_means_tem$december),
                       latitude = "Temperate")) %>%
      select(-march, -june, -september, -december)

  ggplot(insol_rel) +
      geom_line(aes(time, deficit)) +
      facet_wrap(~latitude, ncol = 1) +
      labs(title = "Relative Winter-Summer Insolation Change",
           x = "Time (Years)",
           y = "Relative insolation")
#+END_SRC

And that plot shows rather neatly that the deviations from the average
insolation are indeed different at the different latitudes looked at.

*** Isotope data
First let's have a look at the degree of concordance between GRIP
(red), GISP (orange, with the 6 \permil offset for the GISP data) and
Vostok (blue) data
#+BEGIN_SRC R :file output/isotope_concordance.pdf
  ggplot() +
      geom_line(aes(time, del18O), data = grip, color = "red") +
      geom_line(aes(time, del18O - 6), data = gisp, color = "orange") +
      geom_line(aes(time, 40 + deuterium / 5), data = vostok, color = "blue") +
      scale_y_continuous(sec.axis = sec_axis(~. * 5 - 8,
                         name = expression(paste(delta ^{2}, 'H')))) +
      labs(title = "Isotope data from Greenland and Antarctica Ice Cores",
           x = "Time (Years)",
           y = expression(paste(delta ^{18}, 'O')))

#+END_SRC

Here, we get a hint of a possible problem: the various peaks and
troughs observed in the Greenland and Antarctic do not appear to
coincide all the time, and the direction of changes is also not always
in step. This needs to be resolved one way or another before we can
even begin to look at possible correlations with insolation changes.

Let's look in a little more detail:
#+BEGIN_SRC R :file output/isotope_concordance_detail.pdf
  ggplot() +
      geom_line(aes(time, del18O), data = grip, color = "red") +
      geom_line(aes(time, del18O - 6), data = gisp, color = "orange") +
      geom_line(aes(time, 40 + deuterium / 5), data = vostok, color = "blue") +
      xlim(0, 150000) +
      scale_y_continuous(sec.axis = sec_axis(~. * 5 - 8,
                         name = expression(paste(delta ^{2}, 'H')))) +
      labs(title = "Isotope data from Greenland and Antarctica Ice Cores",
           x = "Time (Years)",
           y = expression(paste(delta ^{18}, 'O')))

#+END_SRC

Something we have to keep in mind is that the Antarctic signal is
determined from the Hydrogen isotope fractionation, while the
Greenland signal uses Oxygen isotope fractionation. This may be
relevant: the overall behaviour appears to be the same, i.e., the
colder intervals show up as more negative fractionations in both
isotopes. However, there are situations in which the signals go in
opposite direction:
#+BEGIN_SRC R :file output/deuterium_oxygen_detail.pdf
  ggplot() +
      geom_line(aes(time, del18O), data = grip, color = "red") +
      geom_line(aes(time, del18O - 6), data = gisp, color = "orange") +
      geom_line(aes(time, 40 + deuterium / 5), data = vostok, color = "blue") +
      xlim(0, 12000) +
      scale_y_continuous(sec.axis = sec_axis(~. * 5 - 8,
                         name = expression(paste(delta ^{2}, 'H')))) +
      labs(title = "Isotope data from Greenland and Antarctica Ice Cores",
           x = "Time (Years)",
           y = expression(paste(delta ^{18}, 'O')))

#+END_SRC

The most obvious difference between Antarctic and Greenland signals is
that the Antarctic signal shows a small but sustained negative
trend. 

A closer look at the 10-12 kYBP interval shows the Antarctic Deuterium
signal ending on a high around 11250 YBP and then gradually
declining. In contrast, the Greenland Oxygen signals rose very fast
around 11600 YBP, and then continue their increase, albeit much more
slowly, until 10000 YBP, from when on they stabilise.

In addition, there is also a clear inversion between the two around
8300 YBP: the GRIP and GISP Oxygen signals show a negative spike,
while the Vostok Deuterium signal shows a positive spike.

The most problematic culprit is the dating. How accurate are the ages,
indeed, how are these determined?

First off, let's have a look at the relations between depth and age?
#+BEGIN_SRC R :file output/age_depth.pdf
  ggplot() +
      geom_line(aes(depth, time), data = grip, color = "red") +
      geom_line(aes(depth, time), data = gisp, color = "orange") +
      geom_line(aes(depth, time), data = vostok, color = "blue") +
      labs(title = "Age versus Depth",
           y = "Time (Years)",
           x = "Depth (m)")
#+END_SRC

The GRIP timescale, ss09, was used by \citet{johnsen-al97:eemian} and
is based on modeling by \citet{dansgaard-johnsen69:model}

*** Relations between insolation and isotope data
How do these insolation differences relate to the GRIP ice signals?
#+BEGIN_SRC R :file output/insol_grip.pdf
  insol_del %>%
      group_by(time) %>%
      summarise(delta = sum(deficit)) %>%
      ungroup() %>%
      ggplot() +
      geom_line(aes(time, delta), color = 'blue') +
      geom_line(aes(time, 30*del18O + 1600),
                data = grip, color = 'red') +
      scale_y_continuous(sec.axis = sec_axis(~. / 30 - 53.3,
                         name = expression(paste(delta ^{18}, 'O')))) +
      xlim(0,250000) +
      labs(title = "Insolation Deficit and GRIP O isotope",
           x = "Time (Years)",
           y = "Cumulated Mean Daily Insolation Deficit (W/m2)")

#+END_SRC

And, what about the Vostok signals?
#+BEGIN_SRC R :file output/insol_vostok.pdf
  insol_del %>%
      group_by(time) %>%
      summarise(delta = sum(deficit)) %>%
      ungroup() %>%
      ggplot() +
      geom_line(aes(time, 5*deuterium + 2800),
                data = vostok, color = 'red') +
      geom_line(aes(time, delta), color = 'blue') +
      scale_y_continuous(sec.axis = sec_axis(~. / 5 - 560,
                         name = expression(paste(delta ^{2}, 'H')))) +
      xlim(0,450000) +
      labs(title = "Insolation Deficit and Vostok Deuterium",
           x = "Time (Years)",
           y = "Cumulated Mean Daily Insolation Deficit (W/m2)")

#+END_SRC

Maybe more can be gleaned from the relative insolation changes?
For Greenland, that gives
#+BEGIN_SRC R :file output/insol_rel_grip.pdf
  insol_rel %>%
      filter(latitude == "Temperate") %>%
      ggplot() +
      geom_line(aes(time, del18O),
                data = grip, color = 'red') +
      geom_line(aes(time, 20 * deficit - 60)) +
      scale_y_continuous(sec.axis = sec_axis(~. / 20 + 3)) +
      xlim(0,150000) +
      labs(title = "GRIP O isotope and Relative Insolation Deficit",
           x = "Time (Years)",
           y = expression(paste(delta ^{18}, 'O')))
#+END_SRC

and for Antarctica
#+BEGIN_SRC R :file output/insol_rel_vostok.pdf
  insol_rel %>%
      filter(latitude == "Temperate") %>%
      ggplot() +
      geom_line(aes(time, deuterium),
                data = vostok, color = 'red') +
      geom_line(aes(time, 100 * deficit - 550)) +
      scale_y_continuous(sec.axis = sec_axis(~. / 100 + 5.5)) +
      xlim(0,250000) +
      labs(title = "Vostok Deuterium and Relative Insolation Deficit",
           x = "Time (Years)",
           y = expression(paste(delta ^{2}, 'H')))
#+END_SRC

** Alternative approaches
Correlation is not causation, and the direct coupling between
temperature/ice volume and received solar radiation is too
simplistic. The redistribution of heat absorbed and emitted by the
oceans and the atmosphere, the various relaxation times of the heat
absorption and (re)emission processes, all that in response to an
oscillatory supply of solar energy (at a variety of different
timescales) suggests that coming up with reasonable causality-driven
models will not be easy.

\citet{maslov14:self-organisation} characterisation of the
exogenous-driven Milankovitch-like approaches as Ptolemaic is rudely
dismissive, but not without substance. However, his proposed purely
endogenous alternative takes that approach too far in turn. The
Lotka-Volterra differential equations can lead to varying oscillatory
behaviours in response to changes in the various constants of the base
equations, but that begs the questions to what extent the physical
processes can be described as such differential equations, and, if so,
how the equation constants can be determined from the known physical
properties of the relevant elements described by the equations.

[Question. Can we differentiate between ice volume and temperature
changes, e.g., by using both Oxygen and Deuterium signals?]

** Analytical Issues
A crucial measure in all the analyses, models and discussions is the
concentration of CO_{2}. Concentrations can be, and have been,
measured directly by capturing air bubbles trapped in ice. Once ice
cores are no longer available, proxies have been used to estimate
concentrations. Going through the literature, I keep coming across
problematic statements about the way in which data are obtained. The
(physicochemical) analytical techniques really need close and critical
scrutiny as the trustworthiness of the data is unfortunately not a
given.
*** Greenland-Antarctica Ice-based CO_{2} concordance
A discrepancy has been noted between the direct CO_{2} measurements in
Greenland and Antarctic ice cores (i.e., from the trapped air
bubbles). \citet{anklin-al95:processes} set out to try and explain why
the Greenland values are much in excess, compared to coeval Antarctic
values. Part of the analysis deals with analytical issues, i.e., the
techniques used to liberate and measure the CO_{2} content.

Looking at the graph provided to help and explain at least part of the
differences (their figure 4) prompted me to extract the data for a
closer look.

First, let's reproduce their graphs
#+BEGIN_SRC R :file output/anklin_fig4.pdf
  anklin_greenland <- read.delim("data/eurocore.dat", skip = 1)
  anklin_antarctica <- read.delim("data/antarcticad47.dat", skip = 1)

  anklin <- anklin_greenland %>%
      mutate(origin = "Greenland") %>%
      gather("Technique","CO2",2:3) %>%
      bind_rows(mutate(anklin_antarctica, origin = "Antarctica") %>%
                gather("Technique", "CO2", 2:3))
  ggplot(anklin) +
      geom_point(aes(Age_AD, CO2, shape = Technique)) +
      facet_grid(~origin)

#+END_SRC
Having reproduced their graphs, this time side by side and with the
same scales, there is quite a bit of detail worth investigating.

It appears that there is not much in the way of systematic offset
between the Dry extraction technique measurements. Can we see this
more clearly?
#+BEGIN_SRC R :file output/anklin_box.pdf
  ggplot(anklin, aes(Technique, CO2)) +
      geom_boxplot() +
      facet_grid(~origin)
      
#+END_SRC
Yes, there is a small systematic offset between the Antarctic and the
Greenland ice when CO_{2} is determined by the dry extraction
technique. There may well be a significant local variation in the
CO_{2} concentrations as captured by the Greenland ice. Also, there
are more Greenland ice samples running over a wider timeframe than
Antarctic samples. Let's put this on a more quantitative footing
#+BEGIN_SRC R
  anklin %>%
      select(-Age_AD) %>%
      group_by(Technique, origin) %>%
      summarise(Average = mean(CO2, na.rm = TRUE),
                Sigma = sd(CO2, na.rm = TRUE))
#+END_SRC
Just to confirm
#+BEGIN_SRC R
  co2g <- anklin %>%
      filter(Technique == "Dry", origin == "Greenland") %>%
      select(CO2)
  co2a <- anklin %>%
      filter(Technique == "Dry", origin == "Antarctica") %>%
      select(CO2)
  t.test(co2g, co2a)
#+END_SRC
The 8 ppm offset between the Greenland and Antarctic mean values is
statistically significant, and claimed by
\citet{anklin-al95:processes} to be too large to be due to
interhemispherical imbalances.

The melt-refreeze technique in turn shows a very substantial
systematic deviation as well as a great deal of spread. That is a
disturbing result. Looking at the standard deviations, we see that
while the standard deviations obtained from the dry extraction
technique are small, and similar to the measurement precision, the
deviations for the melt-refreeze technique are very large, and
essentially the same, both for the Greenland and the Antarctic
samples. 

The differences between the averages are certainly problematic, but
the very large variability of the melt-refreeze technique alone is
more than sufficient to remove any data so generated from
consideration. The 8 ppm offset between the two datasets using the dry
technique may well be not an issue: looking at the plots provided by
https://gml.noaa.gov/ccgg/trends/gl_trend.html, differences from 8 to
12 ppm between Barrow, Alaska and Antarctica have been a regular,
yearly recurrence for the last decade. If anything, the graph strongly
suggests that the Antarctic atmosphere is somehow ``buffered'', as
both the intensity of the yearly oscillations and the secular trend
are substantially smaller and behind the other stations.

The conclusion that the melt-refreeze technique is not fit for purpose
is inescapable.

*** Boron as proxy for CO_{2}
My earlier mentioned unease is strengthened even further after looking
a little more closely into the attempts to determine, or estimate, the
earlier, geological, CO_{2} concentrations
\citep{haynes-honisch20:inventory}. There is no question that clear
and well-defined changes have been documented in the stratigraphic
record (isotopic composition, amounts of CaCO_{3}, and the
like). However, the explanations and mechanisms suggested are at best
tentative, as so many assumptions are made, but remain untested
(delving into the Boron-based work is disheartening: the careful work
done on a few extant planktonic species in the lab already shows the
need for caution, so transplanting that approach to extinct lineages
is not good practice at all. So many questions arise, none of which
are addressed. Not good. 

Take \citet{delavega-al20:piacenzian} discussion. First, let's get the
data (digitising their figure 1), which incorporates data from the
sources listed here

| core | species    | study                                  |
|------+------------+----------------------------------------|
|  999 | ruber      | \citet{martinez-boti-al15:sensitivity} |
|  999 | sacculifer | \citet{seki-al10:alkenone}             |
|  926 | sacculifer | \citet{sosdian-al18:neogene}           |
|  999 | sacculifer | \citet{bartoli-al11:pliocene}          |

Note that for some unexplained reason, the y-axis with the pCO_{2}
values on their figure 1 is logarithmic, and not linear.
#+BEGIN_SRC R :file output/delavega_co2.pdf
  delavega_boron <- read.delim("data/delavega2020_boron.dat", skip = 5)

  ggplot(delavega_boron) +
      geom_point(aes(Age, Boron, colour = study)) +
      geom_line(aes(Age, Boron, colour = study)) +
      labs(title = "de la Vega Fig 1 pCO2 from Boron in Pliocene Foraminifera",
           x = "Time (kY)",
           y = "pCO2") +
      theme(legend.position = "bottom")
#+END_SRC
This is an eloquent and unfortunate graph. The discrepancies in Boron
values recorded in the same core by the planktonic foraminiferal
species /Globigerinoides ruber/ and /Globigerinoides sacculifer/ at
similar (same?) sample depths routinely exceed the variations recorded
over the time interval in one and the same species. This is
fundamentally problematical.

Their publication provides a link to supplementary materials,
including a spreadsheet with data. Let's compare this with the data
culled from the graph in the original paper.
#+BEGIN_SRC R :file output/delavega_supp.pdf
  delavega_sm <- read.delim("data/delavega2020_sm.dat", skip = 5)

  ggplot(delavega_sm) +
      geom_point(aes(Age, d11B, colour = Study)) +
      geom_line(aes(Age, d11B, colour = Study)) +
      labs(title = "de la Vega spreadsheet Boron offsets in Pliocene Foraminifera",
           x = "Time (kY)",
           y = expression(paste(delta ^{11}, 'B'))) +
      theme(legend.position = "bottom")
#+END_SRC
And, for their calculations of the CO_{2} changes
#+BEGIN_SRC R :file output/delavega_supp_co2.pdf
  ggplot(delavega_sm) +
      geom_point(aes(Age, pCO2.av, colour = Study)) +
      geom_line(aes(Age, pCO2.av, colour = Study)) +
      labs(title = "de la Vega spreadsheet CO2 from Boron in Pliocene Foraminifera",
           x = "Time (kY)",
           y = "pCO2") +
      theme(legend.position = "bottom")
#+END_SRC
There is a significant discrepancy between the data tabulated in the
supplementary materials document and the data plotted on their figure
1: no data points lie above the 400 pCO_{2} mark, while the
spreadsheet data does contain significantly higher values. Note also
the anomalous calculation of pCO_{2} from the Boron values from the
Seki data: from boron values of around 18 (with only one single data
point in the de la Vega data set falling to such a low value) arriving
at pCO_{2} concentrations on a par with boron values of 19.5 in the
Martinez-Boti and de la Vega data cannot be justified.

It seems like a good idea to go back to the original publications and
try to obtain the data from there.

So, let's turn to the \citet{martinez-boti-al15:sensitivity}
directly. Fortunately, the supplementary materials of the article
contains a spreadsheet with data of interest.
#+BEGIN_SRC R :file output/martinez_supp.pdf
  martinez_sm <- read.delim("data/martinez2015_boron.dat", skip = 5)

  ggplot(martinez_sm) +
      geom_point(aes(Age, Boron, colour = Site)) +
      geom_line(aes(Age, Boron, colour = Site)) +
      labs(title = "Martinez-Boti Boron offsets in Pliocene Foraminifera",
           x = "Time (kY)",
           y = expression(paste(delta ^{11}, 'B'))) +
      theme(legend.position = "bottom")
#+END_SRC

And, after calculations (and assumptions!) by the authors, estimates
of CO_{2}
#+BEGIN_SRC R :file output/martinez_supp_co2.pdf
  ggplot(martinez_sm) +
      geom_pointrange(aes(Age, pCO2, ymin=pCO2cil, ymax=pCO2ciu, colour = Site)) +
      geom_line(aes(Age, pCO2, colour = Site)) +
      labs(title = "Martinez-Boti CO2 from Boron in Pliocene Foraminifera",
           x = "Time (kY)",
           y = "pCO2") +
      theme(legend.position = "bottom")
#+END_SRC
Clearly, the originally published data do show pCO_{2} values well in
excess of the 400 mark, quite a few reaching 450. So much for the
\citet{delavega-al20:piacenzian} publication.

A separate study by \citet{dyez-al18:variability} likewise contains a
lot of Boron data.
#+BEGIN_SRC R :file output/dyez_boron.pdf
  dyez_boron <- read.delim("data/dyez2018.dat", skip = 4)

  ggplot(dyez_boron) +
      geom_point(aes(Age, Boron, colour = Site)) +
      geom_line(aes(Age, Boron, colour = Site)) +
      labs(title = "Boron offsets by Dyez et al., 2018",
           x = "Time (kY)",
           y = expression(paste(delta ^{11}, 'B'))) +
      theme(legend.position = "bottom")
#+END_SRC

Using a set of assumptions, these lead to the following proposed
atmospheric CO_{2} concentrations.
#+BEGIN_SRC R :file output/dyez_co2.pdf
  ggplot(dyez_boron) +
      geom_point(aes(Age, co2_atmosphere, colour = Site)) +
      geom_line(aes(Age, co2_atmosphere, colour = Site)) +
      labs(title = "Atmospheric CO2 by Dyez et al., 2018",
           x = "Time (kY)",
           y = expression(paste(mu, 'atm'))) +
      theme(legend.position = "bottom")

#+END_SRC

The wild variations shown on these graphs do not inspire much
confidence. Let's turn to some statistics of this data set, and
compare the \delta\isotope{11}{B} values for the different
geochronological stages
#+BEGIN_SRC R
  dyez_boron %>%
      filter(Age < 12) %>%
      mutate(Stage = "Holocene") %>%
      rbind(filter(dyez_boron, Age > 10 & Age < 2600) %>%
      mutate(Stage = "Pleistocene")) %>%
      rbind(filter(dyez_boron, Age > 2600) %>%
      mutate(Stage = "Pliocene")) %>%
      group_by(Site, Stage) %>%
      summarise(average = mean(Boron), sigma = sd(Boron), n = n())
#+END_SRC

Clearly, no significant differences can be seen between the
measurements in the three different stages, what is very much at
variance with what one would expect from the knowledge we have of the
different climatic conditions during those stages.  The differences
between the Sites only serve to stress the point that differentiation
is essentially meaningless for this dataset.

The time has come to take a careful, critical, look at the nature of
the link between boron and CO_{2} and the methods and techniques to
measure the isotopic composition of boron.

*** Boron basics
A boron isotopic standard has been prepared and certified by NIST
\citep{catanzaro-al70:boric}, SRN-951, as boric acid H_{3}BO_{3}, with
an absolute isotopic abundance ratio of 0.2473(2), or 
| isotope         |  proportion |
|-----------------+-------------|
| \isotope{10}{B} | 0.19827(13) |
| \isotope{11}{B} | 0.80173(13) |

\delta\isotope{11}{B} is calculated by
\begin{equation}
\delta\isotope{11}{B}(\permil) = \Bigg(\Bigg( \bigg(\frac{\isotope{11}{B}}{\isotope{10}{B}}\bigg)_{\mathrm{sample}} / 
\bigg(\frac{\isotope{11}{B}}{\isotope{10}{B}}\bigg)_{951}\Bigg) - 1 \Bigg) 1000
\end{equation}

\citet{dickson-goyet94:co2-seawater} listed the standard composition
of seawater as
| Species       | \mole\per\kilogram (sol) | \mole\per\kilogram (H_{2}O) |
|---------------+--------------------------+-----------------------------|
| Cl^{-}        |                  0.54586 |                     0.56576 |
| SO_{4}^{2-}   |                  0.02824 |                     0.02927 |
| Br^{-}        |                  0.00084 |                     0.00087 |
| F^{-}         |                  0.00007 |                     0.00007 |
| Na^{+}        |                  0.46906 |                     0.48616 |
| Mg^{2+}       |                  0.05282 |                     0.05475 |
| Ca^{2+}       |                  0.01028 |                     0.01065 |
| K^{+}         |                  0.01021 |                     0.01058 |
| Sr^{2+}       |                  0.00009 |                     0.00009 |
| B(OH)_{3}     |                  0.00032 |                     0.00033 |
| B(OH)_{4}^{-} |                  0.00010 |                     0.00010 |
| CO_{2}        |                  0.00001 |                     0.00001 |
| HCO_{3}^{-}   |                  0.00177 |                     0.00183 |
| CO_{3}^{2-}   |                  0.00026 |                     0.00027 |
| OH^{-}        |                  0.00001 |                     0.00001 |

In a recent study, \citet{foster-al10:boron} refined the boron numbers
somewhat to a concentration of \unit{432.6}{\micro\mole\per\kilogram}
seawater and specified a \delta\isotope{11}{B} of $39.61\pm
0.04\permil$. From which we deduce the boron isotopic composition of
seawater as
| isotope         | proportion |
|-----------------+------------|
| \isotope{10}{B} | 0.192167   |
| \isotope{11}{B} | 0.807833   |

Boron is present in seawater as boric acid in equilibrium with the
orthoborate ion, as shown in the reaction
\begin{equation}
\mathrm{B(OH)}_3 + \mathrm{H}_2\mathrm{O} \rightleftharpoons \mathrm{H}^+ + \mathrm{B(OH)}_4^-
\label{eqn:borate-equilibrium}
\end{equation}
The equilibrium constant K_{B} for this reaction is temperature and
salinity dependent, and determined by
\citet{dickson90:boric,dickson-goyet94:co2-seawater} as
\begin{equation}
\begin{split}
\ln K_B & = \frac{1}{T}\bigg( -8966.90 - 2890.53\, \sqrt{S} - 77.942\, S + 1.728\, \sqrt{S^3} - 0.0996\, S^2 \bigg) \\
        & + (148.0248 + 137.1942\, \sqrt{S} + 1.62142\, S) \\
        & + (-24.4344 - 25.085\, \sqrt{S} - 0.2474\, S) \ln T \\
        & + 0.053105\, \sqrt{S}\, T
\end{split}
\end{equation}
This equation gives us a means to evaluate the sensitivity of the
equilibrium to changes in salinity and temperature
#+BEGIN_SRC R :file output/boron_pKB.pdf
  lnKB <- function(T, S = 35.0){
      (-8966.9 - 2890.53 * sqrt(S) - 77.942 * S +
       1.728 * S^(3/2) - 0.0996 * S^2) / T +
      (148.0248 + 137.1942 * sqrt(S) + 1.62142 * S) +
      (-24.4344 -25.085 * sqrt(S) - 0.2474 * S) * log(T) +
       0.053105 * T * sqrt(S)
  }

  boron_k <- data.frame(T = seq(275, 300), S = 30.0) %>%
      rbind(data.frame(T = seq(275, 300), S = 32.5)) %>%
      rbind(data.frame(T = seq(275, 300), S = 35.0)) %>%
      rbind(data.frame(T = seq(275, 300), S = 37.5)) %>%
      rbind(data.frame(T = seq(275, 300), S = 40.0)) %>%
      mutate(pKB = -lnKB(T, S) / log(10),
             Salinity = as.factor(S))

  ggplot(boron_k) +
      geom_line(aes(T, pKB, colour = Salinity)) +
      labs(title = "Boric Acid Equilibrium constant in seawater",
           x = "T(Kelvin)",
           y = "pK") +
      theme(legend.position = "bottom")
#+END_SRC
The plot indicates that a difference of \unit{1}{\kelvin} has
approximately the same effect as a difference of \unit{2}{\permil}
salinity on the equilibrium constant (about 3%).

Equation \ref{eqn:borate-equilibrium} can be rewritten so that we can
calculate the concentration of B(OH)^{-}_{4}, assuming a constant
overall boron concentration [B], at present
\unit{0.00043}{\mole\per\kilogram}
\begin{equation}
[\mathrm{B(OH)}^-_4] = \frac{K_B \, [\mathrm{B}]}{[\mathrm{H}^+] + K_B}
\label{eqn:borate_concentration}
\end{equation}
which brings in the dependency on the pH of seawater.

#+BEGIN_SRC R :file output/boron_pH.pdf
  boron_total <- 0.00043
  boron_pH <- data.frame(pH = seq(6, 11, 0.1), T = 283) %>%
      rbind(data.frame(pH = seq(6, 11, 0.1), T = 288)) %>%
      rbind(data.frame(pH = seq(6, 11, 0.1), T = 293)) %>%
      mutate(o_boron = exp(lnKB(T, S = 35)) * boron_total /
                 (10^(-pH) + exp(lnKB(T, S = 35)))) %>%
      mutate(Temperature = as.factor(T))

  ggplot(boron_pH) +
      geom_line(aes(pH, o_boron*1e6, colour = Temperature)) +
      labs(title = "Seawater [o-Borate] pH dependence",
           x = "pH",
           y = expression(paste('[o-Borate] (', mu, 'mol/kg)'))) +
      theme(legend.position = "bottom")
#+END_SRC

As boron is naturally made up by two isotopes, fractionation will take
place in any chemical reaction. That is to say, the equilibium
reaction shown above really is a double reaction:
\begin{equation}
\begin{split}
\isotope{10}{B}\mathrm{(OH)}_3 + \mathrm{H}_2\mathrm{O} & \rightleftharpoons \mathrm{H}^+ + \isotope{10}{B}\mathrm{(OH)}_4^- \\
\isotope{11}{B}\mathrm{(OH)}_3 + \mathrm{H}_2\mathrm{O} & \rightleftharpoons \mathrm{H}^+ + \isotope{11}{B}\mathrm{(OH)}_4^- 
\end{split}
\label{eqn:borate-isotopes}
\end{equation}
The initial attempt to determine the equilibrium cross constant by
\citet{kakihana-al77:ionexchange} found it to deliver a relative
enrichment of \isotope{10}{B} in the anion B(OH)^{-}_{4} with a weak
temperature dependence.

#+tblname: kakihana
|     T | K_isoB |
|-------+--------|
| 273.1 | 1.0206 |
| 278.1 | 1.0204 |
| 288.1 | 1.0199 |
| 298.1 | 1.0194 |
| 313.1 | 1.0187 |
| 323.1 | 1.0182 |
| 333.1 | 1.0177 |

Subsequent additional studies re-evaluated these numbers;
\citet{klochko-al06:fractionation} proposed the
temperature-independent higher value of 1.0272 (or
\unit{27.2}{\permil} enrichment of \isotope{10}{B} of the
B(OH)^{-}_{4}), based on pH measurements of isotopically pure
compounds. The implications of the shift from 1.0194 to 1.0272 on the
calculation of pH, and from there CO_{2} concentrations is
uncomfortably large.

\citet{klochko-al06:fractionation} arrived at their higher values
through pH measurements based on the following reasoning. The
equilibrium equation \ref{eqn:borate-equilibrium} leads directly to
\begin{equation}
\mathrm{pH} = \mathrm{pK}_B + \log \frac{[\mathrm{B(OH)}^-_4]}{[\mathrm{B(OH)}_3]}
\end{equation}
Applying this formula to the equilibrium equation
\ref{eqn:borate-isotopes} we can calculate the differences as
\begin{equation}
\Delta \mathrm{pH} = \mathrm{pK}_{\isotope{11}{B}} - \mathrm{pK}_{\isotope{10}{B}} + \log \frac{[\isotope{10}{B}\mathrm{(OH)}^-_4][\isotope{11}{B}\mathrm{(OH)}_3]}{[\isotope{10}{B}\mathrm{(OH)}_3][\isotope{11}{B}\mathrm{(OH)}^-_4]}
\end{equation}
Here, Klochko makes the assumption that when identical, separate
solutions are made with the two isotopes, then
\begin{equation}
\frac{[\isotope{10}{B}\mathrm{(OH)}_3]}{[\isotope{10}{B}\mathrm{(OH)}^-_4]} = \frac{[\isotope{11}{B}\mathrm{(OH)}_3]}{[\isotope{11}{B}\mathrm{(OH)}^-_4]}
\end{equation}
Clearly, then
\begin{equation}
\Delta \mathrm{pH} = \mathrm{pK}_{\isotope{11-10}{B}}
\end{equation}
allowing the direct measurement through the difference in pH of the
fractionation, as long as the conditions are identical for the two
solutions. Their results in synthetic seawater are

| H_{3}BO_{3} (\mole\per\kilogram) | T (\kelvin) |  K_{\isotope{11-10}{B}} | 2 \sigma | n |
|----------------------------------+-------------+--------+----------+---|
|                             0.01 |         298 | 1.0272 |   0.0006 | 5 |
|                             0.05 |         298 | 1.0257 |   0.0012 | 4 |
|                             0.05 |         298 | 1.0273 |   0.0003 | 4 |
|                             0.05 |         298 | 1.0270 |   0.0019 | 6 |
|                             0.05 |         313 | 1.0269 |   0.0027 | 6 |

while in pure water we get

| H_{3}BO_{3} (\mole\per\kilogram) | T (\kelvin) |  K_{\isotope{11-10}{B}} | 2 \sigma | n |
|-------------+-----+--------+----------+---|
|        0.05 | 298 | 1.0308 |   0.0023 | 6 |
|        0.05 | 313 | 1.0289 |   0.0048 | 6 |

which shows that the ionic strength of seawater, at least at
\unit{298}{\kelvin}, significantly reduces the fractionation as
compared to pure water.

There is an important caveat to be made here. The necessary assumption
that identical solutions of the borate will have identical proportions
of boric acid to the borate ion is not verified. More importantly,
from first principles I would expect there to be a difference: the
heavier isotope will make the transition from the trihedral boric acid
to the tetrahedral borate ion configuration less easily than is the
case for the lighter isotope.

Now to calculate and predict the \delta\isotope{11}{B} of seawater as
a function of pH, and temperature. Starting from equation
\ref{eqn:borate_concentration} we can bring in the isotopes, so that we get
\begin{equation}
\frac{[\isotope{11}{B}\mathrm{(OH)}^-_4]}{[\isotope{10}{B}\mathrm{(OH)}^-_4]} = \frac{[\isotope{11}{B}] \mathrm{K}_{\isotope{11}{B}}}{[\isotope{10}{B}] \mathrm{K}_{\isotope{10}{B}}} \frac{[\mathrm{H}^+] + \mathrm{K}_{\isotope{10}{B}}}{[\mathrm{H}^+] + \mathrm{K}_{\isotope{11}{B}}}
\end{equation}
But we do not have direct access to the isotopicaly pure equilibrium
constants, there is only the function obtained by
\citet{dickson90:boric}. However, we can use the relation of the
fractionation constant
\begin{equation}
\mathrm{K}_{\isotope{11-10}{B}} = \frac{\mathrm{K}_{\isotope{10}{B}}}{\mathrm{K}_{\isotope{11}{B}}}
\end{equation}
and the (untested) assumption that the equilibrium constant K_{B} is
in fact the weighted average of the isotopically pure constants, i.e.,
\begin{equation}
\mathrm{K}_{\mathrm{B}} = \frac{[\isotope{11}{B}]}{[\mathrm{B}]} \mathrm{K}_{\isotope{11}{B}} + \frac{[\isotope{10}{B}]}{[\mathrm{B}]} \mathrm{K}_{\isotope{10}{B}}
\end{equation}
Setting the proportions of isotopes to total boron concentrations as R, we obtain
\begin{equation}
\begin{split}
\mathrm{K}_{\isotope{10}{B}} & = \mathrm{K}_{\mathrm{B}} \frac{\mathrm{K}_{\isotope{11-10}{B}}}{R_{11} + R_{10} \mathrm{K}_{\isotope{11-10}{B}}} \\
\mathrm{K}_{\isotope{11}{B}} & = \mathrm{K}_{\mathrm{B}} \frac{1}{R_{11} + R_{10} \mathrm{K}_{\isotope{11-10}{B}}}
\end{split}
\end{equation}

Let's see how these equations behave, and what the response is to
different temperatures
#+BEGIN_SRC R :file output/borate_fractionation.pdf
  #K11_10 <- 1.019                     # Kakihana et al., 1977 value
  K11_10 <- 1.0272                     # Klochcko et al., 2006 value

  B10_sea <- 0.192167
  B11_sea <- 0.807833
  R_sea<- B11_sea / B10_sea

  B10_951 <- 0.19827
  B11_951 <- 0.80173
  R_951 <- B11_951 / B10_951

  K_10B <- K11_10 / (B11_sea + B10_sea * K11_10)
  K_11B <- 1 / (B11_sea + B10_sea * K11_10)

  boron_delta <- data.frame(pH = seq(7, 9, 0.1), T = 286) %>%
      rbind(data.frame(pH = seq(7, 9, 0.1), T = 288)) %>%
      rbind(data.frame(pH = seq(7, 9, 0.1), T = 290)) %>%
      mutate(K_B = exp(lnKB(T, S = 35))) %>%
      mutate(B_ratio = R_sea / K11_10 * (10^(-pH) + K_B * K_10B)/
                 (10^(-pH) + K_B * K_11B)) %>%
      mutate(delta_B = (B_ratio / R_951 - 1) * 1000,
             Temperature = as.factor(T))

  ggplot(boron_delta) +
      geom_line(aes(pH, delta_B, colour = Temperature)) +
      labs(title = "Borate fractionation in function of pH",
           x = "pH",
           y = expression(paste(delta ^{11}, "B"))) +
      theme(legend.position = "bottom")
#+END_SRC
Note that \citet{klochko-al06:fractionation} use a curve at
\unit{298}{\kelvin}, which puts it even higher than the curves shown here
(average seawater temperature is closer to \unit{290}{\kelvin}). The
rather poor fit of their curve to the values measured in experiments
with planktonic foraminifera becomes worse when using the curve
corresponding to \unit{290}{\kelvin}.

An interesting insight into the sensitivity to pH and temperature can
be gained from the following query:
#+BEGIN_SRC R
  boron_delta %>% filter(pH == 8.1 | pH == 8.3) %>%
      select(pH, T, delta_B) %>%
      arrange(pH, T)
#+END_SRC

#+RESULTS[7fca570c0df0d4da0e28370f1da963c41e7a9f74]:
:    pH   T  delta_B
: 1 8.1 286 17.16365
: 2 8.1 288 17.40407
: 3 8.1 290 17.64943
: 4 8.3 286 19.35042
: 5 8.3 288 19.65940
: 6 8.3 290 19.97184



An ever greater sensitivity is to be found in the value of the
fractionation constant, as already pointed out by
\citet{klochko-al06:fractionation}.

The study by
\citet{tonarini-al07:intercomparison,gonfiantini-al07:intercomparison}
adds further to the troubles of the \delta\isotope{11}{B} story. The
actual measurement of the isotopic proportion is and remains
surprisingly fickle, to the point where confidence intervals on
reported numbers are uncomfortably wide. Here are the results obtained
by 10 different labs, analysing an homogenous sample of
(Mediterranean) seawater.

#+TBLNAME: tonarini
| lab | \delta\isotope{11}{B} | \sigma |  n | technique |
|-----+-----------------------+--------+----+-----------|
| A   |                 36.69 |   0.15 |  5 | PTIMS     |
| B   |                 37.26 |   0.22 |  2 | PTIMS     |
| C   |                 38.84 |    0.4 |  6 | PTIMS     |
| D   |                 39.42 |   0.03 |  3 | PTIMS     |
| E   |                  40.8 |   0.12 | 11 | PTIMS     |
| F   |                 38.85 |   0.83 |  8 | NTIMS     |
| G   |                 39.34 |   0.14 |  4 | NTIMS     |
| H   |                  37.3 |    0.9 |    | ICP-MS    |
| I   |                  33.7 |    6.4 |  4 | ICP-MS    |
| J   |                 34.75 |     20 |    | ICP-MS    |

A simple plot shows all too clearly the problematic outcome of this
exercise. In view of the very large standard deviations reported for 2
of the ICP-MS analyses, these are omitted from the plot.

#+BEGIN_SRC R :var tonarini=tonarini :file output/tonarini.pdf
  names(tonarini) <- c("Lab", "delta_B", "sigma", "n", "technique")

  tonarini %>%
      filter(sigma < 6) %>%
      mutate(delta_B_m = delta_B - 2 * sigma,
             delta_B_M = delta_B + 2 * sigma) %>%
      ggplot() +
      geom_pointrange(aes(Lab, delta_B, ymin=delta_B_m, ymax=delta_B_M)) +
      labs(title = "Interlaboratory Comparative Analysis of Sea water",
           y = expression(paste(delta ^{11}, "B"))) +
      facet_wrap(~technique, scales = "free_x")
#+END_SRC

Clearly, the values and standard deviations of the analyses as
reported are wide off the mark given the PTIMS population sample mean
and standard deviation of \unit{38.6\pm1.66}{\permil}. Harking back to
the graphs of the various data sets published and shown above, one
cannot avoid the conclusion that the analytical techniques and
protocols are insufficiently reliable and mature to allow any
fine-grained analysis of palaeo-CO_{2} levels.

** A first principles approach
Earth receives essentially all its energy from the Sun (heat loss due
to cooling of the core and radiogenic heating amounts to
\unit{42}{\terad\watt}, compared to the \unit{174}{\petad\watt}
for the total solar energy delivered to the Earth). 

In the absence of tectonic activity and of human interference, this
received energy undergoes a number of conversions before ultimately
being radiated out. The various conversion processes have their own
response time, and they interact with each other. This results in a
dynamic equilibrium, maintaining the temperature on Earth within
fairly narrow bounds.

A clear distinction has to be made between the changes in CO_{2} and
CH_{4} concentrations and climate oscillations pre-Anthropocene and
what is taking place now that a massive injection of CO_{2} has taken
place, geologically speaking instantaneously. Pre-Anthropocene, the
greenhouse gases did not drive climate change, if anything, they were
part of the feedback responses. It is not at all clear if the
geological concentrations and the temperatures/ice volumes can be used
as a direct, simple proxy for the effects of the human-caused
concentrations.

The behaviour of CO_{2} also needs scrutiny. Sinks, both temporary
(e.g., dissolved in seawater) and long-term ones (e.g. carbonates) and
sources, deserve attention. Here, too, the transfer between reservoirs
and the characteristic times of residence and transfer, are relevant.

- Hydrosphere
  - Cryosphere (volume, area)
  - Oceans (temperature, heat content, CO_{2}, volume)
- Atmosphere
  - Water vapour (volume, heat content)
  - Clouds (volume, heat content)
  - Precipitation (volume, heat content)
  - CO_{2} (amount, solubility)
  - Temperature
- Energy
  - Incoming Solar Radiation
  - Outgoing Earth Radiation

Energy transfers
- Evaporation
- Condensation
- Heating
- Cooling
- Radiation
- Reflection (albedo)
- Absorption (albedo)

*** Ice
The glacial-interglacial alternations characterising the Pleistocene,
with ice volumes freezing and melting require substantial amounts of
energy. Indeed, the latent heat of freezing/melting of water amounts
to \unit{334}{\kilo\joule\per\kilogram}.

| T (\kelvin) | c_{p} (\joule\per\kilogram\usk\kelvin) | \rho (\kilogram\per\metre\cubed) |
|-------------+----------------------------------------+----------------------------------|
| 273         | 2050                                   | 916.2                            |
| 268         | 2027                                   | 917.5                            |
| 263         | 2000                                   | 918.9                            |
| 258         | 1972                                   | 919.4                            |
| 253         | 1943                                   | 919.4                            |
| 248         | 1913                                   | 919.6                            |
| 243         | 1882                                   | 920.0                            |

We can estimate the amount of energy required to make the
Pleistocene-Holocene transition from the change in sea level. The Last
Glacial Maximum was characterised by a sea level drop of some
\unit{125}{\metre}. \citet{charette-smith10:volume} give the global
ocean area to be \unit{361.84}{\megad\kilo\metre\squared}. Hence the
volume of ice that disappeared equates to
\unit{45.23}{\petad\metre\cubed}, or, with a density of
\unit{916.5}{\kilogram\per\metre\cubed}, some
\unit{41.44}{\exad\kilogram}. To melt such an amount of ice then
requires \unit{13.837}{\yottad\joule}.

It is sobering to reflect on the estimate by \citet{cheng-al23:heat}
of the additional amount of heat stored in the oceans since the
1980ies of about \unit{350}{\zettad\joule}. That translates into an
amount of energy enough to melt ice that would raise the global sea
level with \unit{3.16}{\metre}.

*** Atmosphere
\citet{trenberth-smith05:atmosphere} provide a carefully argued
calculation of the total mass of the atmosphere.

The total mean mass amounts to \unit{5.1480}{\exad\kilogram} with an
annual range due to water vapour of \unit{1.5}{\petad\kilogram}. The
mean mass of water vapour is estimated as \unit{12.7}{\petad\kilogram}
and the dry air mass as \unit{5.1352}{\exad\kilogram}.

Composition of the atmosphere
| component | fraction | mol mass |
|-----------+----------+----------|
| N_{2}     |   0.7808 |  28.0134 |
| O_{2}     |   0.2094 |  31.8888 |
| Ar        |   0.0093 |   39.948 |
| CO_{2}    |   0.0004 |  43.8998 |
which yields an average mol mass for air of 28.9395

\citet{mlynczak-al16:spectroscopic} used a set of atmospheric
profiles, based on the studies by
\citet{mcclatchey-al72:atmosphere}. These profiles include pressure,
temperature, water and ozone content in function of height,
differentiating tropical, mid-latitude and subarctic latitudes as well
as summer/winter differentiation.

Let's have a quick, first look at the data, with pressures in Pa,
temperature in K, and water content in \gram\per\metre\cubed
#+BEGIN_SRC R :file output/atmosphere_profile.pdf
  atm_equ <- read.table("data/grl54358_atmosphere_tropical.dat",
                         col.names = c("height", "pressure",
                                       "temperature", "water", "ozone"),
                         skip = 2) %>%
      mutate(pressure = pressure * 100,
             latitude = "Equatorial") %>%
      select(-ozone)

  atm_mid_s <- read.table("data/grl54358_atmosphere_midlat_summer.dat",
                           col.names = c("height", "pressure",
                                       "temperature", "water", "ozone"),
                           skip = 2) %>%
      mutate(pressure = pressure * 100,
             latitude = "Temperate",
             season = "Summer") %>%
      select(-ozone)

  atm_mid_w <- read.table("data/grl54358_atmosphere_midlat_winter.dat",
                           col.names = c("height", "pressure",
                                       "temperature", "water", "ozone"),
                           skip = 2) %>%
      mutate(pressure = pressure * 100,
             latitude = "Temperate",
             season = "Winter") %>%
      select(-ozone)

  atm_pol_s <- read.table("data/grl54358_atmosphere_subarctic_summer.dat",
                           col.names = c("height", "pressure",
                                       "temperature", "water", "ozone"),
                           skip = 2) %>%
      mutate(pressure = pressure * 100,
             latitude = "Polar",
             season = "Summer") %>%
      select(-ozone)

  atm_pol_w <- read.table("data/grl54358_atmosphere_subarctic_winter.dat",
                           col.names = c("height", "pressure",
                                       "temperature", "water", "ozone"),
                           skip = 2) %>%
      mutate(pressure = pressure * 100,
             latitude = "Polar",
             season = "Winter") %>%
      select(-ozone)

  atmosphere <- atm_equ %>%
      gather("property", "value", 2:4) %>%
      bind_rows(gather(atm_mid_s, "property", "value", 2:4)) %>%
      bind_rows(gather(atm_mid_w, "property", "value", 2:4)) %>%
      bind_rows(gather(atm_pol_s, "property", "value", 2:4)) %>%
      bind_rows(gather(atm_pol_w, "property", "value", 2:4))

  ggplot(atmosphere) +
      geom_line(aes(height, value, colour = season)) +
      facet_wrap(~latitude+property, scales = "free_y") +
      theme(legend.position = "bottom") +
      labs(x = "Height (km)")

#+END_SRC

*** Solar energy spectrum
By comparing the solar radiation spectrum as it is emitted with that
measured at the Earth's surface, we get information on how and how
much energy is captured by the greenhouse gases, i.e., water vapour,
CO_{2} and CH_{4}. Bringing in their absorption spectra should give us
the means to calculate how much heat is retained as a function of
their concentrations in the atmosphere. The principle appears simple,
practice seems to present quite some difficulties.

The Sun radiates energy out, the spectrum of which can be described
remarkably well as that of a black body. That principle can of course
also be applied to the Earth.

Black body radiation was first analysed and described by
\citet{planck00:energieverteilung} as
\begin{equation}
u(\nu, T) = \frac{8 \pi \nu^2}{c^3} \frac{h \nu}{e^{h \nu / k T} - 1}
\end{equation}
with \nu the frequency of the radiation. Integrating over all the
frequencies yields
\begin{equation}
\begin{split}
U(T) & = \int_0^\infty = \frac{8 \pi \nu^2}{c^3} \frac{h \nu}{e^{h \nu / k T} - 1} \\
     & = \frac{8 \pi^2}{60 c^3 h^3}k^4 T^4 \\
     & = \frac{4}{c} \sigma T^4
\end{split}
\end{equation}
with \sigma the Stefan-Boltzman constant (as a combination of the
other constants, we can calculate this very easily as
\unit{56.70373}{\nano\watt\per\metre\squared\fourth\kelvin}). Note
that the usual relation for black body radiation
\begin{equation}
R(T) = \sigma T^4
\end{equation}
is the result of additional, and very much needed, integration over
all the angles of radiation of the previous integration: that one
addresses the ``uni-directional'' flux of energy.

There is a caveat to be heeded here. The relation between frequency
and wavelength cannot be used as is to convert the calculations from
frequency-based values to wavelength-based ones, that is to say
\begin{equation}
\begin{split}
u(\lambda, T) d\lambda & = -u(\epsilon, T) d\epsilon \\
\frac{d\epsilon}{d\lambda} & = -\frac{h c}{\lambda^2}
\end{split}
\end{equation}
and hence we get
\begin{equation}
u(\lambda, T) = \frac{8 \pi h c}{\lambda^5} \frac{1}{e^{h c /\lambda k T} - 1}
\end{equation}

Let's see this distribution for the Sun, with a temperature of some
\unit{5778}{\kelvin} 
#+BEGIN_SRC R :file output/solar_spectrum.pdf
  T_sun <- 5778
  a1 <- 8 * pi * h_planck * c_light
  a2 <- h_planck * c_light / (k_boltzmann * T_sun)

  sun_energy <- data.frame(lambda = seq(100, 5000, 10)*1e-9) %>%
      mutate(Energy = a1 / (lambda^5 * (exp(a2 / lambda) - 1)))

  ggplot(sun_energy) +
      geom_line(aes(lambda*1e9, Energy)) +
      labs(title = "Solar Radiation, Black Body at 5778 K",
           x = "Wavelength (nm)",
           y = "Energy (J/m3.m)")

#+END_SRC

Let's check these calculations and equations, and compare the
(numerical) integration of the curve with the calculated energy, i.e.,
#+BEGIN_SRC R
  sun_integral <- (sum(sun_energy$Energy) * 1e-8 )
  sun_blackbody <- sigma_stefan * T_sun^4

  (sun_integral * c_light / 4) / sun_blackbody
#+END_SRC

That confirms the numerical calculations: in addition, a dimensional
analysis likewise confirms the correctness of the need for the speed
of light as part of the final calculation
(\joule\per\metre\cubed $\times$ \metre\per\second $=$
\watt\per\metre\squared).

In order to calculate the actual energy distribution arriving on
Earth, we need to scale the black body spectrum just calculated, that
is to say, reduce it to the amount of energy arriving at the
Earth. Let's turn to the insolation calculated earlier on from 
\citet{laskar-al04:insolation}.

#+BEGIN_SRC R :file output/solar_incoming.pdf
  insolation %>%
      group_by(time) %>%
      summarise(energy=mean(power)) %>%
      ggplot() +
      geom_line(aes(time, energy)) +
      ylim(200, 400) +
      labs(title = "Global yearly Average Insolation",
           x = "Time (Years BP)",
           y = "Energy (W/m2)")
#+END_SRC

And so we can confirm that that we do have
\unit{341.57}{\watt\per\metre\squared} coming in, averaged over the
globe and over the year. That allows us now to scale the energy of the
solar spectrum arriving at the Earth
#+BEGIN_SRC R :file output/solar_spectrum_scaled.pdf
  solar_incoming <- 341.57
  scale_factor <- solar_incoming * c_light / (4 * sigma_stefan * T_sun^4)

  sun_energy %<>%
      mutate(Energy = Energy * scale_factor)

  ggplot(sun_energy) +
      geom_line(aes(lambda*1e9, Energy)) +
      labs(title = "Incoming Solar Radiation profile",
           x = "Wavelength (nm)",
           y = "Energy (W/m3)")
#+END_SRC

A quick check to see if this normalisation is correct:
#+BEGIN_SRC R
  sum(sun_energy$Energy) * 1e-8
#+END_SRC
which is sufficiently close to the expected value of
\unit{341.57}{\watt\per\metre\squared}.

This amount of incoming solar radiation gives us also a means of
assessing to what extent the Earth can be considered as a black
body. The amount of energy arriving at the Earth has to be radiated
out again (if not, the Earth's temperature would increase), we can
calculate the expected black body temperature as
#+BEGIN_SRC R
  (solar_incoming / sigma_stefan)^(1/4)
#+END_SRC
which is about \unit{10}{\kelvin} below the current average Earth
temperature of \unit{288}{\kelvin}. So, as expected, the Earth does
not behave as a black body. In fact, about 30% of the incoming energy
is reflected out \citep{trenberth-al09:budget} implying that the
theoretical black body temperature would be even lower, i.e.,
\unit{254.8}{\kelvin} (and further reinforcing the deviation from
black body assumptions).

In principle, we can calculate the expected black body temperature of
any of the planets, as some elementary algebra tells us that
\begin{equation}
T_{\mathrm{Planet}} = \sqrt{\frac{R_{\mathrm{Sun}}}{2 R_{\mathrm{orbit}}}} \, T_{\mathrm{Sun}}
\end{equation}
assuming of course that any planetary albedo will be zero

So, given a solar radius of \unit{695508}{\kilo\metre} and a
temperature of \unit{5778}{\kelvin}, we predict

| Planet  | distance (km) | T_{Black Body} (K) |
|---------+---------------+--------------------|
| Mercury |      57909227 |             447.75 |
| Venus   |     108209475 |             327.55 |
| Earth   |     149598262 |             278.58 |
| Mars    |     227943824 |             225.68 |
| Jupiter |     778340821 |             122.13 |
| Saturn  |    1426666422 |              90.20 |

Now, looking at the incoming solar radiation, the low amount of energy
in the absorption bands of CO_{2} are obvious.  However, when we turn
to the equivalent black body radiation emitted by the Earth, we get a
different picture. Repeating the earlier calculations for the solar
energy, but this time for the Earth (with an average temperature of
\unit{288}{\kelvin}), and using the estimated value of
\unit{238.5}{\watt\per\metre\squared} of outgoing radiation
\citep{trenberth-al09:budget}, we get
#+BEGIN_SRC R :file output/earth_spectrum.pdf
  T_earth <- 288
  earth_outgoing <- 238.5
  scale_factor <- earth_outgoing * c_light / (4 * sigma_stefan * T_earth^4)

  a1 <- 8 * pi * h_planck * c_light
  a2 <- h_planck * c_light / (k_boltzmann * T_earth)

  earth_energy <- data.frame(lambda = seq(2000, 50000, 200)*1e-9) %>%
      mutate(Energy = a1 / (lambda^5 * (exp(a2 / lambda) - 1)),
             Energy = Energy * scale_factor)

  ggplot(earth_energy) +
      geom_line(aes(lambda*1e6, Energy)) +
      labs(title = "Earth Radiation, Black Body at 288 K",
           x = expression(paste("Wavelength (", mu, "m)")),
           y = "Energy (W/m2)")
#+END_SRC

and so we see that a great deal of (outgoing) energy can be absorbed
by CO_{2}, i.e., the actual greenhouse effect.

*** CO2
**** Solubility in seawater

While a great deal of work has been done on the behaviour and
interactions of CO_{2} and water, that was less the case for
interactions with seawater. The presence of the many different ions in
seawater is a substantial impediment to physicochemical theories and
calculations: the actual solution is quite a long way off from ideal,
i.e., simplified, conditions.

When CO_{2} dissolves in water, it undergoes a two-step
dissociation.
\begin{eqnarray}
\mathrm{CO}_2 + \mathrm{H}_2\mathrm{O} & \rightleftharpoons & \mathrm{H}^+ + \mathrm{HCO}_3^ \\
\mathrm{HCO}_3^- & \rightleftharpoons & \mathrm{H}^+ + \mathrm{CO}_3^{2-}
\end{eqnarray}

\citet{dickson-goyet94:co2-seawater} gave a suite of standard
procedures and calculations specifically to deal with CO_{2} and
seawater. Amongst the useful equations, there is one to calculate the
fugacity of CO_{2} as a component of a binary mixture
\begin{equation}
f = [x] p e^{(\frac{B_x(T) + 2 [x]^2 \delta_{xy}(T)) p}{R T}}
\end{equation}

The first virial coefficient B can be calculated with an expression
derived by \citet{weiss74:solubility}
\begin{equation}
B(T) = -1636.75 + 12.0408 T - 3.27957 10^{-2} T^2 + 3.16528 10^{-5} T^3
\end{equation}
valid for $265 < T < 320$, with T(\kelvin) and
B(\centi\cubic\metre\per\mole).

He also derived a means to estimate the cross virial coefficient for
the CO_{2}-air mixture as
\begin{equation}
\delta(T) = 57.7 - 0.118 T
\end{equation}
valid for $273 < T < 313$, again with T(\kelvin) and
\delta(\centi\cubic\metre\per\mole).

The equilibrium constant K$_0$ for the reaction 
\begin{equation}
\mathrm{CO}_2(g) \rightleftharpoons \mathrm{CO}^*_2(aq) 
\end{equation}
(where CO$^*_2$ stands for sum of $[\mathrm{CO}_2(aq)] + [\mathrm{HCO}_3^-] + [\mathrm{CO}_3^{2-}]$)
that is to say
\begin{equation}
K_0 = \frac{[\mathrm{CO}^*_2]}{f(\mathrm{CO}_2)}
\end{equation}
comes again from \citet{weiss74:solubility} and is given as
\begin{equation}
\ln K_0 = 93.4517 \frac{100}{T} - 60.2409 + 23.3585 \ln \frac{T}{100} + S (0.023517 - 0.023656 \frac{T}{100} + 0.0047036 (\frac{T}{100})^2)
\end{equation}
where the fugacity is expressed in atmospheres and the salinity S

And so we can calculate for any given CO_{2} concentration in the air
how much will be dissolved in seawater at a temperature T.
#+BEGIN_SRC R
  # Include conversion from cm3 to m3
  delta <- function(T){(57.7 - 0.118 * T) * 1e-6}

  b0 <- -1636.75
  b1 <- 12.0408
  b2 <- -3.279571e-2
  b3 <- 3.165281e-5

  # Include conversion from cm3 to m3
  virial <- function(T){(b0 + b1 * T + b2 * T^2 + b3 * T^3) * 1e-6}

  e0 <- 93.4517
  e1 <- -60.2409
  e2 <- 23.3585
  e3 <- 0.023517
  e4 <- -0.023656
  e5 <- 0.0047036

  lnK0 <- function(T, S = 35){
      e0 * 100/T + e1 + e2 * log(T/100) + S * (e3 + e4 * T/100 + e5 *(T/100)^2)}

  fugacity <- function(x, T, p){
      x * p * exp((virial(T) + 2 * x^2 * delta(T)) * p / (R_gas * T))}

  # the K0 calc assumes atmospheres, so bring in the Pa conversion with p0
  co2aq <- function(x, T, p, S = 35){
      exp(lnK0(T, S)) / p0 * fugacity(x, T, p)}
#+END_SRC

Having defined the various functions, let's have a look at the nature
of the relations: include the pre-industrial (green line) and the
present CO_{2} concentrations (blue line).

#+BEGIN_SRC R :file output/co2sol.pdf
  co2sol <- data.frame(T = seq(273, 300)) %>%
      mutate(co2_280 = co2aq(280e-6, T, p0),
             co2_420 = co2aq(420e-6, T, p0))

  ggplot(co2sol) +
      geom_line(aes(T, co2_280*1e6), colour = "blue") +
      geom_line(aes(T, co2_420*1e6), colour = "green") +    
      labs(title = "CO2 solubility in seawater",
           x = "T (K)",
           y = expression(paste('[CO2(aq)] (', mu, 'mol/kg)')))
#+END_SRC

**** Energy Absorption
The next step in the process is accounting for the absorption by
CO_{2}, and also H_{2}O as parts of their absorption spectra overlap.

A great deal of meticulous effort has been expended on obtaining these
absorption spectra, including quantum mechanical calculations
\citep{rothman-al2009:hitran,lamouroux-al12:database,etminan-al16:forcing,mlynczak-al16:spectroscopic}.
These efforts have culminated into a database which can be accessed
on-line (https://hitran.org/) to obtain any desired data.  The level
of detail captured in the database includes the separation of each
isotope of the constituent atoms. The most abundant isotopic mix is
marked with code number 1.

A complete explanation of the  HITRAN data structure is as follows:

| parameter     | field length | format | units                                                                         |
|---------------+--------------+--------+-------------------------------------------------------------------------------|
| M             |            2 | I2     | HITRAN molecule number code                                                   |
| I             |            1 | I1     | ordering within molecule by terrestrial abundance                             |
| \nu           |           12 | F12.6  | \centi\reciprocal\metre                                                       |
| S             |           10 | E10.3  | \centi\reciprocal\metre\per\centi\rpsquare\metre molecule               |
| A             |           10 | E10.3  | \reciprocal\second                                                            |
| \gamma_{air}  |            5 | F5.4   | HWHM at \unit{296}{\kelvin} (\centi\reciprocal\metre atm^{-1})                |
| \gamma_{self} |            5 | F5.4   | HWHM at \unit{296}{\kelvin} (\centi\reciprocal\metre atm^{-1})                |
| E''           |           10 | F10.4  | \centi\reciprocal\metre                                                       |
| n_{air}       |            4 | F4.2   | exponent of \gamma_{air}                                                      |
| \delta_{air}  |            8 | F8.6   | \centi\reciprocal\metre atm^{-1}                                              |
| V'            |           15 | A15    | Upper state global quanta                                                     |
| V''           |           15 | A15    | Lower state global quanta                                                     |
| Q'            |           15 | A15    | Upper state local quanta                                                      |
| Q''           |           15 | A15    | Lower state local quanta                                                      |
| Ierr          |            6 | 6I1    | accuracy codes for \nu, S, \gamma_{air}, \gamma_{self}, n_{air}, \delta_{air} |
| Iref          |           12 | 6I2    | references for \nu, S, \gamma_{air}, \gamma_{self}, n_{air}, \delta_{air}     |
| flag          |            1 | A1     |                                                                               |
| g'            |            7 | F7.1   | weight of upper state                                                         |
| g''           |            7 | F7.1   | weight of lower state                                                         |

The two molecules on interest in the analysis here are H_{2}O (1) and
CO_{2} (2). A query of the database for the most common isotopologues
of these two molecules and including all the wavelengths for which
data is available, yielded 319887 entries for H_{2}O and 174446
entries for CO_{2}.

A neat way of bringing in the data is through an AWK script. Although
the data is presented in a Fortran-type format, i.e., columnar, there
is a possibility of defining fields by their width, rather than the
usual AWK field separator character.

#+BEGIN_SRC awk :in-file data/hitran_co2.par :file cache/hitran_co2.dat :results none
  BEGIN{OFS = ","
      FIELDWIDTHS = "2 1 12 10 10 5 5 10 4 8 60 6 12 1 7 7"
        print "nu, intensity, Einstein_A, gamma_air, gamma_self, \
               energy_lower, n_air, delta_air"}
      {print $3, $4, $5, $6, $7, $8, $9, $10
  }
#+END_SRC

#+BEGIN_SRC awk :in-file data/hitran_h2o.par :file cache/hitran_h2o.dat :results none
  BEGIN{OFS = ","
      FIELDWIDTHS = "2 1 12 10 10 5 5 10 4 8 60 6 12 1 7 7"
        print "nu, intensity, Einstein_A, gamma_air, gamma_self, \
               energy_lower, n_air, delta_air"}
      {print $3, $4, $5, $6, $7, $8, $9, $10
  }
#+END_SRC

The shape of an absorption peak is not as straightforward a matter as
one might expect. An absorption line is broadened around its
transition wavelength due to temperature, pressure, and presence of
other molecules \citep{tennyson-al14:IUPAC}. In the lower atmosphere,
the broadening of a line is largely driven by collisions with other
molecules, and can be modeled by a Lorentz profile:
\begin{equation}
f_L(\nu; \nu_{ij}, p, T) = \frac{1}{\pi} \frac{\gamma(p, T)}{\gamma(p, T)^2 + (\nu - \nu^*_{ij})^2}
\end{equation}
where
\begin{equation}
\begin{split}
\gamma(p, T) & = \Bigg( \frac{T_0}{T} \Bigg)^{n_{air}} \bigg( \gamma_{air}(p_0, T_0)(p - p_{self}) + \gamma_{self}(p_0, T_0) p_{self} \bigg) \\
\nu_{ij}^* & = \nu_{ij} + \delta p_0 p
\end{split}
\end{equation}
In addition, the thermal translational movement of the molecules also
causes a Doppler effect, which shows up as a frequency shift. The
resulting profile can be described by a Gaussian curve, 
\begin{equation}
F_D(\nu - \nu_0) = \sqrt{\frac{\ln 2}{\pi}} \frac{1}{\Gamma_D} e^{-\ln 2 (\frac{\nu - \nu_0}{\Gamma_D})^2}
\end{equation}
with \Gamma_{D} the Doppler half-width
\begin{equation}
\Gamma_D = \sqrt{\frac{2 \ln 2 k T}{m c^2}} \nu_0
\end{equation}
To account for both effects, these two profiles can be convoluted into
a Voigt Profile
\begin{equation}
I(\nu) = \int^{\infty}_{-\infty} G(\nu') L(\nu - \nu') d\nu'
\end{equation}
which needs to be evaluated numerically \citep{thompson93:voigt}.

Fortunately, a fortran package with associated data files
\citep{gordon-al22:hitran2020,lamouroux-al15:linemixing} is freely
available from https://hitran.org/supplementary/ and allows for easy
experimentation.  The following variables can be changed before
carrying out the calculations

| variable | unit                    | description                   |
|----------+-------------------------+-------------------------------|
| SgMinR   | \centi\reciprocal\metre | Minimum wavenumber            |
| SgMaxR   | \centi\reciprocal\metre | Maximum wavenumber            |
| dSg      | \centi\reciprocal\metre | Wavenumber step size          |
| sTotMax  |                         | Band intensity cut-off        |
| Temp     | K                       | Temperature                   |
| Ptot     | atm                     | Total pressure                |
| xCO2     |                         | CO_{2} mole fraction          |
| xH2O     |                         | H_{2}O mole fraction          |
| MixFull  | logical                 | Full line mixing calcs        |
| MixSDV   | logical                 | Speed-dependent Voigt profile |

The results of the calculations are stored in a file, all in
\centi\reciprocal\metre

| entry | description                                                  |
|-------+--------------------------------------------------------------|
| nu    | wave number                                                  |
| AbsV  | Absorption coeffcient using Voigt line shape, no line mixing |
| AbsY  | Absorption coefficient, first-order line mixing              |
| AbsW  | Absorption coefficient, full diagonalisation line mixing     |

As an example, here is the result of the mixing calculations centered
around an absorpion peak at \unit{4.24}{\micro\metre} (or, in the cgs
units used by the code, \unit{150}{\centi\reciprocal\metre} around
\unit{2361}{\centi\reciprocal\metre})

#+BEGIN_SRC R :file output/hitran_2350.pdf
  hitran_2350 <- read.table("data/hitran_lm_2350.dat",
                            col.names = c("nu","Voigt","First_Order","Full_Calc"))

  ggplot(hitran_2350) +
      geom_line(aes(nu, Full_Calc)) +
      labs(title = "Absorption Coefficients, with Full line mixing",
           x = expression(paste('Wave number ', (cm^{-1}))),
           y = expression(paste('Absorption Coefficient ', (cm^{-1}))))
#+END_SRC

It is a straightforward matter to calculate the area under the curves
(sum of all the values multiplied with the step size), and so we can
assess the contributions of the various absorption bands. As the
interval spans \unit{150}{\centi\reciprocal\metre}, the maximum area
under the curve would stand at
\unit{150}{\centi\reciprocal\metre}. Clearly, the amount of radiation
absorption at these concentrations is small.

| wave number \centi\reciprocal\metre | \micro\metre |  IAbs_V |  IAbs_f |  IAbs_F |
|-------------------------------------+--------------+---------+---------+---------|
|                                 667 |         15.0 | 0.09658 | 0.09657 | 0.09664 |
|                                2361 |         4.24 | 1.07069 | 1.07141 | 1.07130 |
|                                3625 |         2.76 | 0.01197 | 0.01197 | 0.01197 |
|                                3727 |         2.68 | 0.01775 | 0.01776 | 0.01776 |
|                                4990 |         2.00 | 0.00039 | 0.00040 | 0.00040 |
|                                5114 |         1.95 | 0.00013 | 0.00013 | 0.00013 |

There are more bands present in the database, but their individual
peak absorptions are less that 10^{-6} and can be neglected for our
purposes.

Let's explore the effects of changes in CO_{2} concentration,
pressure, and temperature on the integrated absorption, using the the
strongest peak (around \unit{2361}{\centi\reciprocal\metre}) as
reference. The reference value is calculated with the following settings

| variable | value        | unit                    |
|----------+--------------+-------------------------|
| dSg      | 0.01         | \centi\reciprocal\metre |
| sTotMax  | 0.1 10^{-28} |                         |
| Temp     | 290          | K                       |
| Ptot     | 1.0          | atm                     |
| xCO2     | 420 10^{-6}  |                         |
| xH2O     | 0            |                         |
| MixFull  | .True.       | logical                 |
| MixSDV   | .False.      | logical                 |

First, let's see what the effect is of changing the CO_{2} mole
percentages

| ppm CO_{2} |  IAbs_V |  IAbs_f |  IAbs_F |
|------------+---------+---------+---------|
|        105 | 0.26767 | 0.26785 | 0.26782 |
|        210 | 0.53534 | 0.53570 | 0.53565 |
|        420 | 1.07069 | 1.07141 | 1.07130 |

The expectation of a linear relation between CO_{2} concentration and
absorbance is clearly fulfilled.

The same linear relation between pressure and absorbance is also
clearly recovered
| pressure (atm) |  IAbs_V |  IAbs_f |  IAbs_F |
|----------------+---------+---------+---------|
|            1.0 | 1.07069 | 1.07141 | 1.07130 |
|            0.5 | 0.53553 | 0.53571 | 0.53562 |
|            0.1 | 0.10690 | 0.10690 | 0.10702 |

Changing the temperature yields the following values
#+TBLNAME: Temp_Abs
| Temperature |  IAbs_V |  IAbs_f |  IAbs_F |
|-------------+---------+---------+---------|
|         200 | 1.55429 | 1.55567 | 1.55560 |
|         210 | 1.48013 | 1.48139 | 1.48132 |
|         220 | 1.41270 | 1.41385 | 1.41377 |
|         230 | 1.35112 | 1.35220 | 1.35210 |
|         240 | 1.29467 | 1.29566 | 1.29557 |
|         250 | 1.24271 | 1.24365 | 1.24355 |
|         260 | 1.19477 | 1.19564 | 1.19554 |
|         270 | 1.15036 | 1.15117 | 1.15106 |
|         280 | 1.10910 | 1.10987 | 1.10976 |
|         290 | 1.07069 | 1.07141 | 1.07130 |

And a plot shows that this not a simple linear relation
#+BEGIN_SRC R :var Temp_Abs=Temp_Abs :file output/hitran_TA.pdf
  ggplot(Temp_Abs) +
      geom_point(aes(Temperature, IAbs_F)) +
      xlim(200, 300) +
      labs(title = "Integrated Absorbance in function of Temperature",
           x = "Temperature (K)",
           y = expression(paste('Absorbance ', (cm^{-1}))))
#+END_SRC

*** Calcium carbonate
Note. \delta^{13}C changes in CaCO_{3} are used to infer changes in C
source. As I came across a reference in
\citet{canadell-al21:IPCC6-biogeochemical} on Palaeocene-Eocene
Thermal Maximum \citet{ajayi-al20:evaluation}, I noticed that most, if
not all, of the work is based on bulk sediment samples, i.e., the
carbonate component in the sediment is not split up. This is terrible,
as it conflates a variety of fractionation processes. Changes in
plankton composition (foram/nanno ratio: nannos are photosynthetic,
forams are not), changes in (planktonic) foram species abundance
(globigerinid-like species remaining in the photic zone,
globorotaliid/morozovellid-like species occupying different water
depths over their life cycle), and on top of all that the demonstrated
pH-dependence of the C fractionation, all these varying processes are
conflated, so that there is no way in which to retrieve any changes in
isotope composition due to injection/availability of C sources. Hence,
I cannot trust the published suggestions of differing amounts of C
coming from different sources (e.g., marine, terrestrial, plants,
melting permafrost, \&c.)

As a result, I shall see if I can limit myself to use actual, directly
measured values of CO_{2} and CH_{4} concentrations in air bubbles
trapped in polar ice, and disregard any proxy-based data beyond the
ice record. Then again, see \citet{anklin-al95:processes}. Oh dear.
* Epilogue

** An aside on the possible use of Catastrophy Theory
There are indications that CO_{2} levels have to drop below 300-350
ppm, before glacial-interglacial alternations kick off
\citep{canadell-al21:IPCC6-biogeochemical,delavega-al20:piacenzian}. If
the inferred concentrations of CO_{2} can be made robust (which is an
open question for now, in view of my reservations re the way in which
Boron is used as a proxy), this would be a very good indication that
the approach taken by catastrophe theory may be useful.

A recent survey by \citet{cheng-al23:heat} suggests that heat started
to accumulate in the oceans since around 1985 and this accumulation
has not only continued but has grown now to record levels. The
atmospheric CO_{2} record for 1985 shows that concentrations reached
350 ppm and continued to grow ever since. This recorded combination
suggests that a fundamental tipping point was reached around that
time, and that a return to Pliocene conditions have become
unavoidable.

The scenario would run along these lines. As long as CO_{2}
concentrations remain high enough, the greenhouse effect is
sufficiently large to mitigate the astronomical insolation variation
and maintain a hothouse Earth. As CO_{2} continues to be sequestered
over geological time, a point is reached where the greenhouse effect
can no longer sustain a permanent hothouse Earth, and the
glacial-interglacial alternations become established. Then we need
some quirk in the system so that an interglacial remains locked in
(i.e., the stable last interglacial). The massive injection of CO_{2}
of the Anthropocene to concentrations encountered well before the
glacial-interglacial alternations would then kick the entire system
back to a hothouse Earth (after the various biogeochemical cycles have
adjusted to a new equilibrium).

The energy input into the Earth system is astronomically determined
(control 1). The atmospheric CO_{2} concentration determines (to a
large extent, but how large?) the amount of heat captured from the
insolation (control 2). The (average) Earth temperature is a
consequence of the captured heat (behaviour). 

Of course, there are important complications. The atmospheric CO_{2}
is the result of a partitioning between atmosphere and hydrosphere
(the latter temperature dependent). And then there are the various
sequestration processes.

Something similar governs the heat budget as well. The hydrosphere can
store substantial amounts of heat, but this will influence the
redistribution patterns of the oceans. (Another thought: epeiric
basins have all but disappeared, compared to earlier geological
times. That must have a significant(?) influence of the CO_{2} storage
capacity of the oceans; large expanses of water will be warmer, and
store less CO_{2}, possibly/likely draining part of the deep storage
as a result).


\citet{thom72:stabilite}

For any system that seeks to minimize a function, only seven different
local forms of catastrophe ``typically'' occur for four or fewer
variables:

1. Fold catastrophe,
2. Cusp catastrophe,
3. Swallowtail catastrophe,
4. Butterfly catastrophe,
5. Elliptic umbilic catastrophe,
6. Hyperbolic umbilic catastrophe, and
7. Parabolic umbilic catastrophe.

More specifically, for any system with fewer than five control factors
and fewer than three behavior axes, these are the only seven
catastrophes possible. The following tables gives the possible
catastrophes as a function of control factors and behavior axes.

| controls | 1 behaviour | 2 behaviour                          |
|----------+-------------+--------------------------------------|
|        1 | fold        |                                      |
|        2 | cusp        |                                      |
|        3 | swallowtail | hyperbolic umbilic, elliptic umbilic |
|        4 | butterfly   | parabolic umbilic                    |

The following table gives prototypical examples for equations showing each type of catastrophe.
| equation                      | catastrophe                                    |
|-------------------------------+------------------------------------------------|
| $x^3+ux$                      | fold catastrophe                               |
| $x^4+ux^2+vx$                 | cusp catastrophe, Riemann-Hugoniot catastrophe |
| $x^5+ux^3+vx^2+wx$            | swallowtail catastrophe                        |
| $x^3+y^3+uxy+vx+wy$           | hyperbolic umbilic catastrophe                 |
| $x^3/3-xy^2+u(x^2+y^2)+vx+wy$ | elliptic umbilic catastrophe                   |
| $x^6+ux^4+vx^3+wx^2+tx$       | butterfly catastrophe                          |
| $x^2y+y^4+ux^2+vy^2+wx+ty$    | parabolic umbilic catastrophe                  |

* References

\bibliographystyle{plainnat}
\bibliography{climate}

