#+TITLE: Climate Change Explorations
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt,a4paper,titlepage]
#+LATEX_HEADER: \def\today{\number\day\space\ifcase\month\or January\or February\or March\or April\or May\or June\or July\or August\or September\or October\or November\or December\fi \space \number\year}
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage{amssymb,amsmath}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage[round]{natbib}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \usepackage[squaren,cdot]{SIunits}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER: \lhead{}
#+LATEX_HEADER: \rhead{}
#+LATEX_HEADER: \lfoot{Climate Change}
#+LATEX_HEADER: \cfoot{\thepage}
#+LATEX_HEADER: \rfoot{\thedate}
#+LATEX_HEADER_EXTRA: \author{Stefan Revets}
#+LATEX_HEADER_EXTRA: \pretitle{\flushleft\LARGE\bfseries\vskip 80mm}
#+LATEX_HEADER_EXTRA: \posttitle{\par}
#+LATEX_HEADER_EXTRA: \preauthor{\flushleft}
#+LATEX_HEADER_EXTRA: \postauthor{\par}
#+LATEX_HEADER_EXTRA: \predate{\flushleft}
#+LATEX_HEADER_EXTRA: \postdate{\par{In Progress}}
#+OPTIONS: ^:{}

* Introduction
In one of our monthly discussions, Birger asked if there was a proper
understanding of the processes and mechanisms driving climate change
(on a geological timescale). The glacial-interglacial alternations
have been documented to go back some considerable time, and
Milankovitch cycles are usually put forward as explanation. My
impression is that we don't really understand what is going on, but it
seemed only fair to look a little closer into what has been proposed
over the years.

A considerable amount of work has been expended already, using the
Milankovitch cycles as a basis \citep{milankovitch20:theorie},
refining and expanding the processes involved (changes in albedo,
moisture content in the atmosphere, ocean circulation, and so on and
so forth).

Different approaches are few and far in between. A distinct
alternative proposes that the cycles may be endogenous, i.e., the
consequence of behaviour of coupled differential equations describing
the processes of heat transfer in the Earth's system, decoupled and
independent from astronomical driving or forcing
\citep{maslov14:self-organisation}.

Looking at the Oxygen isotope curves from the Greenland and Deuterium
from Antarctic ice cores more closely prompts a whole series of
questions. Why is it that a great many (most?) warming events are
short and abrupt and followed by a much more gradual, lower, cooling
sequence? What happened after the last glacial to bring about an
apparently unprecedented 10 kY of stable climate? The Greenland and
Antarctica isotope curves and CO_{2} curves appear to be quite
similar, but which one changes first? That is, in the (pre-human
intervention) past, are the changing CO_{2} concentrations a cause or
an effect of the temperature changes? What is the role of CO_{2} in
the Dansgaard-Oescher cycles; an enabler, a moderator, an accelerator?
How come that the there is no discernable insolation change comparable
to the Dansgaard-Oescher cycle time intervals?

The curves do show similarities to curves of limit cycles, `chaotic'
systems, or strange attractor systems. It was rather nice then, to
come across a paper \citep{steffen-al18:trajectories} that sketches
this possible mechanism. Another intrigueing discussion was presented
by \citet{baez12:twf319}, and then there is the endogenous,
Lotka-Volterra like modelling as well
\citep{maslov14:self-organisation}.

In order to try and get a better understanding of the whole thing,
taking a step back from all that engrossing, immediate detail, and
going back to first principles seems like a good plan.

At the most fundamental level, the Earth behaves like a heat engine,
powered by the Sun.  The Earth, atmosphere, oceans and land mass,
absorb and emit energy, all of which comes from the Sun. As the Earth
turns around its own axis, around the Sun, rotating on its titled,
wobbling axis, the amount of energy coming down and hence available
for reflection, absorption and emission changes at a wide variety of
time scales. Some of that solar energy is variously trapped by water
vapour, CO_{2} and CH_{4} in the atmosphere, as well as by the oceans
and the continents, and downgraded to heat in the process. Part of
that heat is then radiated out again into space, so that temperature
on Earth remains within limits. There is of course the additional
redistribution across the Earth of the absorbed heat, adding
substantial complexity to the entire process.

\citet{milankovitch20:theorie} used the Stockwell-Pilgrim values for
eccentricity, obliquity and precession to calculate the incoming solar
radiation for latitudes \unit{55}{\degree}, \unit{60}{\degree} and
\unit{65}{\degree} N for the last 500,000 years.

Since that time, the calculation of orbital parameters have continued
to improve \citep{laskar-al04:insolation,laskar-al11:la2010}, and,
more importantly, we now have access to much more precisely dated
palaeotemperatures, in particular temperature data from Greenland and
Antarctica ice cores. In addition, we also have CO_{2} and CH_{4}
measurements from those same ice cores. And so we have everything we
need to (re)calculate the amount of solar energy delivered anywhere on
the Earth and revisit any relations with the temperature changes
recorded in the ice cores.

* Data Sources
** Astronomical Data
Laskar and colleagues have created a website to allow on-line
calculation of insolation given a set of input parameters using the
results published in \citet{laskar-al04:insolation}
(http://vo.imcce.fr/insola/earth/online/earth/online/index.php).

This provides an easy means of getting the data needed here.

A useful measure would be the mean daily insolation. This can be
converted for calculation purposes into a mean longitude as set out in
the table below

| Date         | Mean Longitude | Season   |
|--------------+----------------+----------|
| 21 March     |              0 | equinox  |
| 21 April     |             30 |          |
| 21 May       |             60 |          |
| 21 June      |             90 | solstice |
| 21 July      |            120 |          |
| 21 August    |            150 |          |
| 21 September |            180 | equinox  |
| 21 October   |            210 |          |
| 21 November  |            240 |          |
| 21 December  |            270 | solstice |
| 21 January   |            300 |          |
| 21 February  |            330 |          |

Note that intermediate values can be used if desired.

Other assumptions and setting include the following
- time :: is expressed in Julian years, with a starting/ending point
          of J2000.0.
- solar constant :: \unit{1368}{\watt\per\squaremetre}
- latitudes :: positive for N, negative for S hemisphere
- insolation :: expressed in \watt\per\squaremetre

Let's generate mean daily insolation data for the 4 season onsets over
100 year intervals for the last 1 million years and that at 4
latitudes, and use a naming convention for the data files

| latitude             | name      |
|----------------------+-----------|
| \unit{0}{\degree}    | insol_equ |
| \unit{25}{\degree}   | insol_tro |
| \unit{50}{\degree}   | insol_tem |
| \unit{72.5}{\degree} | insol_pol |

The latitude chosen for the polar region is that of the location of
the GRIP core in Greenland.  Of course, there will be only zeroes for
the winter solstice for the polar latitude. Each of the data files is
made up of the time (expressed in units of thousands of Julian Years,
and negative as we're interested in values before the present) and the
calculated insolation (in \watt\per\squaremetre).

** Temperature Data
GRIP and GISP Oxygen isotope data and Vostok Deuterium data obtained
from the National Snow and Ice Data Center, University of Colorado at
Boulder, and the WDC-A for Paleoclimatology, National Geophysical Data
Center, Boulder, Colorado.

** Atmospheric gases
I still need to track down ice-based CO_{2} and CH_{4} data, ideally
both from Greenland and from Antarctic ice cores. It is important in
that the measurements of these gases also has isotope measurements in
the same samples: interpolation would dilute the reliability of the
data for study and analysis.

** Heat capture
I need to track down the absorption spectrum of CO_{2} and H_{2}O, as
well as the means to calculate the relation between concentration and
amount of heat converted/trapped by these gases from the (incoming)
solar radiation and outgoing radiation.

* Calculations
:PROPERTIES:
:session: *R*
:cache: yes
:results: output graphics
:exports: both
:END:

#+BEGIN_SRC R :results none
  library("dplyr")
  library("ggplot2")
  library("magrittr")
  library("pracma")
  library("tidyr")

  R <- 8.31451          # J / K mol, Gas constant
  p0 <- 101325          # Pa, standard pressure
#+END_SRC

** Data preparation
First of all, let's bring in the insolation data and combine the data
so that we end up with separate data frames for each of the latitudes,
but bringing each of the dates together.

First bring in the data for the equator. In the process, let's change
the time into actual years, and drop the negative. That way, it will
be compatible with the ice core data
#+BEGIN_SRC R :results none
  insol_equ <- read.table("data/insol_equ_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_equ_90.dat",
                           col.names = c('time','june'))
  insol_equ %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_equ_180.dat",
                           col.names = c('time','september'))
  insol_equ %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_equ_270.dat",
                           col.names = c('time','december'))
  insol_equ %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

Now repeat for the other latitudes; first for the tropic of cancer
#+BEGIN_SRC R :results none
  insol_tro <- read.table("data/insol_tro_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_tro_90.dat",
                           col.names = c('time','june'))
  insol_tro %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tro_180.dat",
                           col.names = c('time','september'))
  insol_tro %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tro_270.dat",
                           col.names = c('time','december'))
  insol_tro %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

then for the temperate zone
#+BEGIN_SRC R :results none
  insol_tem <- read.table("data/insol_tem_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_tem_90.dat",
                           col.names = c('time','june'))
  insol_tem %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tem_180.dat",
                           col.names = c('time','september'))
  insol_tem %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_tem_270.dat",
                           col.names = c('time','december'))
  insol_tem %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

and finally for the polar region
#+BEGIN_SRC R :results none
  insol_pol <- read.table("data/insol_pol_0.dat",
                          col.names = c('time','march'))

  insol_temp <- read.table("data/insol_pol_90.dat",
                           col.names = c('time','june'))
  insol_pol %<>%
      left_join(insol_temp, by = 'time')

  insol_temp <- read.table("data/insol_pol_180.dat",
                           col.names = c('time','september'))
  insol_pol %<>%
      left_join(insol_temp, by = 'time') %>%
      mutate(time = time * -1000) %>%
      arrange(time)
#+END_SRC

Now let's get the GRIP and GISP oxygen isotope data as well as the
deuterium data from the Vostok core
#+BEGIN_SRC R :results none
  grip <- read.table("grip/gripd18O.dat",
                     col.names = c('depth','time','del18O'))
  gisp <- read.table("gisp/gispd18O.dat",
                     col.names = c('depth','time','del18O'))
  vostok <-  read.table("vostok/vostok_d.dat",
                        col.names = c('depth', 'time', 'deuterium', 'deltaTS'))
#+END_SRC

** Exploration
*** Insolation
Let's have a look first at the insolation calculations. One obvious
avenue to pursue is to see how the summer-winter differences evolve?

#+BEGIN_SRC R :file output/insol_delta.pdf
  insol_del <- data.frame(time = insol_equ$time,
                          equ_rel = 1 - insol_equ$december/insol_equ$june,
                          tro_rel = 1 - insol_tro$december/insol_tro$june,
                          tem_rel = 1 - insol_tem$december/insol_tem$june,
                          pol_rel = 1)

  insol_del %<>%
      mutate(equ_abs = equ_rel * insol_equ$june,
             tro_abs = tro_rel * insol_tro$june,
             tem_abs = tem_rel * insol_tem$june,
             pol_abs = insol_pol$june,
             delta = equ_abs + tro_abs + tem_abs)

  ggplot(insol_del) +
  #    geom_line(aes(time, delta)) +
      geom_line(aes(time, equ_rel), color = 'blue') +
      geom_line(aes(time, tro_rel), color = 'blue') +
      geom_line(aes(time, tem_rel), color = 'blue') +
  #    geom_line(aes(time, pol), color = 'blue') +
      labs(title = "Relative Summer-Winter Insolation Deficit",
           x = "Time (Years)",
           y = "Relative Deficit")

#+END_SRC

Let's have a look at the differences relative to the mean insolations
for each latitude and find out if these are essentially the same, or
not. Let's offset the three zones from each other in the plot by 0.5,
so that we can see the individual lines more clearly.
#+BEGIN_SRC R :file output/insol_rel.pdf
  insol_means_pol <- summarise_each(insol_pol, funs(mean))
  insol_means_tem <- summarise_each(insol_tem, funs(mean))
  insol_means_tro <- summarise_each(insol_tro, funs(mean))
  insol_means_equ <- summarise_each(insol_equ, funs(mean))

  insol_rel <- data.frame(time = insol_equ$time,
                          equ = (insol_equ$december / insol_means_equ$december)/(insol_equ$june / insol_means_equ$june),
                          tro = (insol_tro$december / insol_means_tro$december)/(insol_tro$june / insol_means_tro$june),
                          tem = (insol_tem$december / insol_means_tem$december)/(insol_tem$june / insol_means_tem$june),
                          pol = 1)

  ggplot(insol_rel) +
      geom_line(aes(time, equ - 0.5), color = 'red') +
      geom_line(aes(time, tro), color = 'green') +
      geom_line(aes(time, tem + 0.5), color = 'blue') +
#      ylim(-1, 1) +
      labs(title = "Relative Summer-Winter Insolation Change",
           x = "Time (Years)",
           y = "Relative summer/winter insolation")

#+END_SRC
And that plot shows rather neatly that the deviations from the average
insolation are indeed different at the different latitudes looked at.

*** Isotope data
First let's have a look at the degree of concordance between GRIP
(red), GISP (orange, with the 6 \permil offset for the GISP data) and
Vostok (blue) data
#+BEGIN_SRC R :file output/isotope_concordance.pdf
  ggplot() +
      geom_line(aes(time, del18O), data = grip, color = "red") +
      geom_line(aes(time, del18O - 6), data = gisp, color = "orange") +
      geom_line(aes(time, 40 + deuterium / 5), data = vostok, color = "blue") +
#      xlim(0, 250000) +
      scale_y_continuous(sec.axis = sec_axis(~. * 5 - 40,
                         name = expression(paste(delta ^{2}, 'H')))) +
      labs(title = "Isotope data from Greenland and Antarctica Ice Cores",
           x = "Time (Years)",
           y = expression(paste(delta ^{18}, 'O')))

#+END_SRC

Here, we get a hint of a possible problem: the various peaks and
troughs observed in the Greenland and Antarctic do not appear to
coincide all the time, and the direction of changes is also not always
in step. This needs to be resolved one way or another before we can
even begin to look at possible correlations with insolation changes.

Let's look in a little more detail:
#+BEGIN_SRC R :file output/isotope_concordance_detail.pdf
  ggplot() +
      geom_line(aes(time, del18O), data = grip, color = "red") +
      geom_line(aes(time, del18O - 6), data = gisp, color = "orange") +
      geom_line(aes(time, 40 + deuterium / 5), data = vostok, color = "blue") +
      xlim(0, 150000) +
      scale_y_continuous(sec.axis = sec_axis(~. * 5 - 40,
                         name = expression(paste(delta ^{2}, 'H')))) +
      labs(title = "Isotope data from Greenland and Antarctica Ice Cores",
           x = "Time (Years)",
           y = expression(paste(delta ^{18}, 'O')))

#+END_SRC

Something we have to keep in mind is that the Antarctic signal is
determined from the Hydrogen isotope fractionation, while the
Greenland signal uses Oxygen isotope fractionation. This may be
relevant: the overall behaviour appears to be the same, i.e., the
colder intervals show up as more negative fractionations in both
isotopes. However, there are situations in which the signals go in
opposite direction:
#+BEGIN_SRC R :file output/deuterium_oxygen_detail.pdf
  ggplot() +
      geom_line(aes(time, del18O), data = grip, color = "red") +
      geom_line(aes(time, del18O - 6), data = gisp, color = "orange") +
      geom_line(aes(time, 40 + deuterium / 5), data = vostok, color = "blue") +
      xlim(0, 12000) +
      scale_y_continuous(sec.axis = sec_axis(~. * 5 - 40,
                         name = expression(paste(delta ^{2}, 'H')))) +
      labs(title = "Isotope data from Greenland and Antarctica Ice Cores",
           x = "Time (Years)",
           y = expression(paste(delta ^{18}, 'O')))

#+END_SRC

The most obvious difference between Antarctic and Greenland signals is
that the Antarctic signal shows a small but sustained negative
trend. 

A closer look at the 10-12 kYBP interval shows the Antarctic Deuterium
signal ending on a high around 11250 YBP and then gradually
declining. In contrast, the Greenland Oxygen signals rose very fast
around 11600 YBP, and then continue their increase, albeit much more
slowly, until 10000 YBP, from when on they stabilise.

In addition, there is also a clear inversion between the two around
8300 YBP: the GRIP and GISP Oxygen signals show a negative spike,
while the Vostok Deuterium signal shows a positive spike.

The most problematic culprit is the dating. How accurate are the ages,
indeed, how are these determined?

First off, let's have a look at the relations between depth and age?
#+BEGIN_SRC R :file output/age_depth.pdf
  ggplot() +
      geom_line(aes(depth, time), data = grip, color = "red") +
      geom_line(aes(depth, time), data = gisp, color = "orange") +
      geom_line(aes(depth, time), data = vostok, color = "blue") +
      labs(title = "Age versus Depth",
           y = "Time (Years)",
           x = "Depth (m)")
#+END_SRC

The GRIP timescale, ss09, was used by \citet{johnsen-al97:eemian} and
is based on modeling by \citet{dansgaard-johnsen69:model}

*** Relations between insolation and isotope data
How do these insolation differences relate to the GRIP ice signals?
#+BEGIN_SRC R :file output/insol_grip.pdf
    ggplot(insol_del) +
        geom_line(aes(time, delta), color = 'blue') +
        geom_line(aes(time, 30*del18O + 1600),
                  data = grip, color = 'red') +
        scale_y_continuous(sec.axis = sec_axis(~. / 30,
                           name = expression(paste(delta ^{18}, 'O')))) +
        xlim(0,250000) +
        labs(title = "Insolation Deficit and GRIP O isotope",
             x = "Time (Years)",
             y = "Cumulated Mean Daily Insolation Deficit (W/m2)")

#+END_SRC

And, what about the Vostok signals?
#+BEGIN_SRC R :file output/insol_vostok.pdf
    ggplot(insol_del) +
        geom_line(aes(time, 5*deuterium + 2800),
                  data = vostok, color = 'red') +
        geom_line(aes(time, delta), color = 'blue') +
        scale_y_continuous(sec.axis = sec_axis(~. / 5,
                           name = 'Deuterium')) +
        xlim(0,450000) +
        labs(title = "Insolation Deficit and Vostok Deuterium",
             x = "Time (Years)",
             y = "Cumulated Mean Daily Insolation Deficit (W/m2)")

#+END_SRC

Maybe more can be gleaned from the relative insolation changes?
For Greenland, that gives
#+BEGIN_SRC R :file output/insol_rel_grip.pdf
    ggplot(insol_rel) +
        geom_line(aes(time, del18O),
                  data = grip, color = 'red') +
        geom_line(aes(time, 15 * tem - 50), color = 'blue') +
        geom_line(aes(time, 15 * tro - 50), color = 'green') +
#        scale_y_continuous(sec.axis = sec_axis(~. / 30,
#                           name = expression(paste(delta ^{18}, 'O')))) +
        xlim(0,150000) +
        labs(title = "Insolation Deficit and GRIP O isotope",
             x = "Time (Years)",
             y = "Relative Summer/Winter Insolation proportion")

#+END_SRC

and for Antarctica
#+BEGIN_SRC R :file output/insol_rel_vostok.pdf
    ggplot(insol_rel) +
        geom_line(aes(time, deuterium),
                  data = vostok, color = 'red') +
        geom_line(aes(time, 100 * tro - 500), color = 'green') +
        geom_line(aes(time, 100 * tem - 500), color = 'blue') +
        xlim(0,250000) +
        labs(title = "Insolation Deficit and Vostok Deuterium",
             x = "Time (Years)",
             y = "Relative Summer/Winter Insolation proportion")

#+END_SRC

** Alternative approaches
Correlation is not causation, and the direct coupling between
temperature/ice volume and received solar radiation is too
simplistic. The redistribution of heat absorbed and emitted by the
oceans and the atmosphere, the various relaxation times of the heat
absorption and (re)emission processes, all that in response to an
oscillatory supply of solar energy (at a variety of different
timescales) suggests that coming up with reasonable causality-driven
models will not be easy.

\citet{maslov14:self-organisation} characterisation of the
exogenous-driven Milankovitch-like approaches as Ptolemaic is rudely
dismissive, but not without substance. However, his proposed purely
endogenous alternative takes that approach too far in turn. The
Lotka-Volterra differential equations can lead to varying oscillatory
behaviours in response to changes in the various constants of the base
equations, but that begs the questions to what extent the physical
processes can be described as such differential equations, and, if so,
how the equation constants can be determined from the known physical
properties of the relevant elements described by the equations.

[Question. Can we differentiate between ice volume and temperature
changes, e.g., by using both Oxygen and Deuterium signals?]

** A first principles approach
Earth receives essentially all its energy from the Sun (heat loss due
to cooling of the core and radiogenic heating amounts to
\unit{42}{\terad\watt}, compared to the \unit{174}{\petad\watt}
for the total solar energy delivered to the Earth). 

In the absence of tectonic activity and of human interference, this
received energy undergoes a number of conversions before ultimately
being radiated out. The various conversion processes have their own
response time, and they interact with each other. This results in a
dynamic equilibrium, maintaining the temperature on Earth within
fairly narrow bounds.

A clear distinction has to be made between the changes in CO_{2} and
CH_{4} concentrations and climate oscillations pre-Anthropocene and
what is taking place now that a massive injection of CO_{2} has taken
place, geologically speaking instantaneously. Pre-Anthropocene, the
greenhouse gases did not drive climate change, if anything, they were
part of the feedback responses. It is not at all clear if the
geological concentrations and the temperatures/ice volumes can be used
as a direct, simple proxy for the effects of the human-caused
concentrations.

The behaviour of CO_{2} also needs scrutiny. Sinks, both temporary
(e.g., dissolved in seawater) and long-term ones (e.g. carbonates) and
sources, deserve attention. Here, too, the transfer between reservoirs
and the characteristic times of residence and transfer, are relevant.

- Hydrosphere
  - Cryosphere (volume, area)
  - Oceans (temperature, heat content, CO_{2}, volume)
- Atmosphere
  - Water vapour (volume, heat content)
  - Clouds (volume, heat content)
  - Precipitation (volume, heat content)
  - CO_{2} (amount, solubility)
  - Temperature
- Energy
  - Incoming Solar Radiation
  - Outgoing Earth Radiation

Energy transfers
- Evaporation
- Condensation
- Heating
- Cooling
- Radiation
- Reflection (albedo)
- Absorption (albedo)

*** Atmosphere
\citet{trenberth-smith05:atmosphere} provide a carefully argued
calculation of the total mass of the atmosphere.

The total mean mass amounts to \unit{5.1480}{\exad\kilogram} with an
annual range due to water vapour of \unit{1.5}{\petad\kilogram}. The
mean mass of water vapour is estimated as \unit{12.7}{\petad\kilogram}
and the dry air mass as \unit{5.1352}{\exad\kilogram}.

Composition of the atmosphere
| component | fraction | mol mass |
|-----------+----------+----------|
| N_{2}     |   0.7808 |  28.0134 |
| O_{2}     |   0.2094 |  31.8888 |
| Ar        |   0.0093 |   39.948 |
| CO_{2}    |   0.0004 |  43.8998 |
which yields an average mol mass for air of 28.9395

*** CO2
**** Solubility in seawater

While a great deal of work has been done on the behaviour and
interactions of CO_{2} and water, that was less the case for
interactions with seawater. The presence of the many different ions in
seawater is a substantial impediment to physicochemical theories and
calculations: the actual solution is quite a long way off from ideal,
i.e., simplified, conditions.

When CO_{2} dissolves in water, it undergoes a two-step
dissociation.
\begin{eqnarray}
CO_2 + H_2O & \rightleftharpoons & H^+ + HCO_3^ \\
HCO_3^- & \rightleftharpoons & H^+ + CO_3^{2-}
\end{eqnarray}

\citet{dickson-goyet94:co2-seawater} gave a suite of standard
procedures and calculations specifically to deal with CO_{2} and
seawater. Amongst the useful equations, there is one to calculate the
fugacity of CO_{2} as a component of a binary mixture
\begin{equation}
f = [x] p e^{(\frac{B_x(T) + 2 [x]^2 \delta_{xy}(T)) p}{R T}}
\end{equation}

The first virial coefficient B can be calculated with an expression
derived by \citet{weiss74:solubility}
\begin{equation}
B(T) = -1636.75 + 12.0408 T - 3.27957 10^{-2} T^2 + 3.16528 10^{-5} T^3
\end{equation}
valid for $265 < T < 320$, with T(\kelvin) and
B(\centi\cubic\metre\per\mole).

He also derived a means to estimate the cross virial coefficient for
the CO_{2}-air mixture as
\begin{equation}
\delta(T) = 57.7 - 0.118 T
\end{equation}
valid for $273 < T < 313$, again with T(\kelvin) and
\delta(\centi\cubic\metre\per\mole).

The equilibrium constant K$_0$ for the reaction 
\begin{equation}
CO_2(g) \rightleftharpoons CO^*_2(aq) 
\end{equation}
(where CO$^*_2$ stands for sum of $[CO_2(aq)] + [HCO_3^-] + [CO_3^{2-}]$)
that is to say
\begin{equation}
K_0 = \frac{[CO^*_2]}{f(CO_2)}
\end{equation}
comes again from \citet{weiss74:solubility} and is given as
\begin{equation}
\ln K_0 = 93.4517 \frac{100}{T} - 60.2409 + 23.3585 \ln \frac{T}{100} + S (0.023517 - 0.023656 \frac{T}{100} + 0.0047036 (\frac{T}{100})^2)
\end{equation}
where the fugacity is expressed in atmospheres and the salinity S

And so we can calculate for any given CO_{2} concentration in the air
how much will be dissolved in seawater at a temperature T.
#+BEGIN_SRC R
  # Include conversion from cm3 to m3
  delta <- function(T){(57.7 - 0.118 * T) * 1e-6}

  b0 <- -1636.75
  b1 <- 12.0408
  b2 <- -3.279571e-2
  b3 <- 3.165281e-5

  # Include conversion from cm3 to m3
  virial <- function(T){(b0 + b1 * T + b2 * T^2 + b3 * T^3) * 1e-6}

  e0 <- 93.4517
  e1 <- -60.2409
  e2 <- 23.3585
  e3 <- 0.023517
  e4 <- -0.023656
  e5 <- 0.0047036

  lnK0 <- function(T, S = 35){
      e0 * 100/T + e1 + e2 * log(T/100) + S * (e3 + e4 * T/100 + e5 *(T/100)^2)}

  fugacity <- function(x, T, p){
      x * p * exp((virial(T) + 2 * x^2 * delta(T)) * p / (R * T))}

  # the K0 calc assumes atmospheres, so bring in the Pa conversion with p0
  co2aq <- function(x, T, p, S = 35){
      exp(lnK0(T, S)) / p0 * fugacity(x, T, p)}
#+END_SRC

Having defined the various functions, let's have a look at the nature
of the relations: include the pre-industrial (green line) and the
present CO_{2} concentrations (blue line).

#+BEGIN_SRC R :file output/co2sol.pdf
  co2sol <- data.frame(T = seq(273, 300)) %>%
      mutate(co2_280 = co2aq(280e-6, T, p0),
             co2_420 = co2aq(420e-6, T, p0))

  ggplot(co2sol) +
      geom_line(aes(T, co2_280*1e6), colour = "blue") +
      geom_line(aes(T, co2_420*1e6), colour = "green") +    
      labs(title = "CO2 solubility in seawater",
           x = "T (Kelvin)",
           y = expression(paste('[CO2(aq)] (', mu, 'mol/kg)')))
#+END_SRC


*** Calcium carbonate

Note. \delta^{13}C changes in CaCO_{3} are used to infer changes in C
source. As I came across a reference in
\citet{canadell-al21:IPCC6-biogeochemical} on Palaeocene-Eocene
Thermal Maximum \citet{ajayi-al20:evaluation}, I noticed that most, if
not all, of the work is based on bulk sediment samples, i.e., the
carbonate component in the sediment is not split up. This is terrible,
as it conflates a variety of fractionation processes. Changes in
plankton composition (foram/nanno ratio: nannos are photosynthetic,
forams are not), changes in (planktonic) foram species abundance
(globigerinid-like species remaining in the photic zone,
globorotaliid/morozovellid-like species occupying different water
depths over their life cycle), and on top of all that the demonstrated
pH-dependence of the C fractionation, all these varying processes are
conflated, so that there is no way in which to retrieve any changes in
isotope composition due to injection/availability of C sources. Hence,
I cannot trust the published suggestions of differing amounts of C
coming from different sources (e.g., marine, terrestrial, plants,
melting permafrost, \&c.)

As a result, I shall see if I can limit myself to use actual, directly
measured values of CO_{2} and CH_{4} concentrations in air bubbles
trapped in polar ice, and disregard any proxy-based data beyond the
ice record. Then again, see \citet{anklin-al95:processes}. Oh dear.

** Analytical Issues
Going through the literature, I keep coming across problematic
statements about the way in which data are obtained. The
(physicochemical) analytical techniques really need close and critical
scrutiny as the trustworthiness of the data is unfortunately not a
given.
*** Greenland-Antarctica CO_{2} concordance
A discrepancy has been noted between the direct CO_{2} measurements in
Greenland and Antarctic ice cores (i.e., from the trapped air
bubbles). \citet{anklin-al95:processes} set out to try and explain why
the Greenland values are much in excess, compared to coeval Antarctic
values. Part of the analysis deals with analytical issues, i.e., the
techniques used to liberate and measure the CO_{2} content.

Looking at the graph provided to help and explain at least part of the
differences (their figure 4) prompted me to extract the data for a
closer look.

First, let's reproduce their graphs
#+BEGIN_SRC R :file output/anklin_fig4.pdf
  anklin_greenland <- read.delim("data/eurocore.dat", skip = 1)
  anklin_antarctica <- read.delim("data/antarcticad47.dat", skip = 1)

  anklin <- anklin_greenland %>%
      mutate(origin = "Greenland") %>%
      gather("Technique","CO2",2:3)

  anklin_tmp <- anklin_antarctica %>%
      mutate(origin = "Antarctica") %>%
      gather("Technique","CO2",2:3)

  anklin <- bind_rows(anklin, anklin_tmp)

  ggplot(anklin) +
      geom_point(aes(Age_AD, CO2, shape = Technique)) +
      facet_grid(~origin)

#+END_SRC
Having reproduced their graphs, this time side by side and with the
same scales, there is quite a bit of detail worth investigating.

It appears that there is not much in the way of systematic offset
between the Dry extraction technique measurements. Can we see this
more clearly?
#+BEGIN_SRC R :file output/anklin_box.pdf
  ggplot(anklin, aes(Technique, CO2)) +
      geom_boxplot() +
      facet_grid(~origin)
      
#+END_SRC
Yes, there is a smallish systematic offset when CO_{2} is determined
by the dry extraction technique. There may well be a significant local
variation in the CO_{2} concentrations as captured by the Greenland
ice. Also, there are more Greenland ice samples running over a wider
timeframe than Antarctic samples. Let's put this on a more
quantitative footing
#+BEGIN_SRC R
  anklin %>%
      select(-Age_AD) %>%
      group_by(Technique, origin) %>%
      summarise(stdev = mean(CO2, na.rm = TRUE))
#+END_SRC
Just to confirm
#+BEGIN_SRC R
  co2g <- anklin %>%
      filter(Technique == "Dry", origin == "Greenland") %>%
      select(CO2)
  co2a <- anklin %>%
      filter(Technique == "Dry", origin == "Antarctica") %>%
      select(CO2)
  t.test(co2g, co2a)
#+END_SRC
While the 8 ppm offset between the Greenland and Antarctic mean values is
statistically significant, it may or may not be overly concerning.

On the other hand, the melt-refreeze technique shows a systematic
deviation as well as a great deal of spread. That is a disturbing
result. A more quantitative assessment of the variability, or spread
of the measurements, can be obtained get from the standard deviations
#+BEGIN_SRC R 
  anklin %>%
      group_by(Technique, origin) %>%
      summarise(stdev = sd(CO2, na.rm = TRUE))
#+END_SRC
So we see that while the standard deviations obtained from the dry
extraction technique are small, and similar to the measurement
precision, the deviations for the melt-refreeze technique are very
large, and essentially the same, both for the Greenland and the
Antarctic samples. There is therefore little justification for a
separate explanation for the Greenland data, as the variability (and
hence unreliability) of the Antarctic data is just as large. If
anything, the conclusion imposing itself is that the melt-refreeze
technique is not fit for purpose.

*** Boron as proxy for CO_{2}
My earlier mentioned unease is strengthened even further after looking
a little more closely into the attempts to determine, or estimate, the
earlier, geological, CO_{2} concentrations
\citep{haynes-honisch20:inventory}. There is no question that clear
and well-defined changes have been documented in the stratigraphic
record (isotopic composition, amounts of CaCO_{3}, and the
like). However, the explanations and mechanisms suggested are at best
tentative, as so many assumptions are made, but remain untested
(delving into the Boron-based work is disheartening: the careful work
done on a few extant planktonic species in the lab already shows the
need for caution, so transplanting that approach to extinct lineages
is not good practice at all. So many questions arise, none of which
are addressed. Not good. 

Take \citet{delavega-al20:piacenzian} discussion. First, let's get the
data (digitising their figure 1), which incorporates data from the
sources listed here

| core | species    | study                                  |
|------+------------+----------------------------------------|
|  999 | ruber      | \citet{martinez-boti-al15:sensitivity} |
|  999 | sacculifer | \citet{seki-al10:alkenone}             |
|  926 | sacculifer | \citet{sosdian-al18:neogene}           |
|  999 | sacculifer | \citet{bartoli-al11:pliocene}          |

Note that for some unexplained reason, the y-axis with the pCO_{2}
values on their figure 1 is logarithmic, and not linear.
#+BEGIN_SRC R :file output/delavega_co2.pdf
  delavega_boron <- read.delim("data/delavega2020_boron.dat", skip = 5)

  ggplot(delavega_boron) +
      geom_point(aes(Age, Boron, colour = study)) +
      geom_line(aes(Age, Boron, colour = study)) +
      labs(title = "de la Vega Fig 1 pCO2 from Boron in Pliocene Foraminifera",
           x = "Time (kY)",
           y = "pCO2") +
      theme(legend.position = "bottom")
#+END_SRC
This is an eloquent and unfortunate graph. The discrepancies in Boron
values recorded in the same core by the planktonic foraminiferal
species /Globigerinoides ruber/ and /Globigerinoides sacculifer/ at
similar (same?) sample depths routinely exceed the variations recorded
over the time interval in one and the same species. This is
fundamentally problematical.

Their publication provides a link to supplementary materials,
including a spreadsheet with data. Let's compare this with the data
culled from the graph in the original paper.
#+BEGIN_SRC R :file output/delavega_supp.pdf
  delavega_sm <- read.delim("data/delavega2020_sm.dat", skip = 5)

  ggplot(delavega_sm) +
      geom_point(aes(Age, d11B, colour = Study)) +
      geom_line(aes(Age, d11B, colour = Study)) +
      labs(title = "de la Vega spreadsheet Boron offsets in Pliocene Foraminifera",
           x = "Time (kY)",
           y = expression(paste(delta ^{11}, 'B'))) +
      theme(legend.position = "bottom")
#+END_SRC
And, for their calculations of the CO_{2} changes
#+BEGIN_SRC R :file output/delavega_supp_co2.pdf
  ggplot(delavega_sm) +
      geom_point(aes(Age, pCO2.av, colour = Study)) +
      geom_line(aes(Age, pCO2.av, colour = Study)) +
      labs(title = "de la Vega spreadsheet CO2 from Boron in Pliocene Foraminifera",
           x = "Time (kY)",
           y = "pCO2") +
      theme(legend.position = "bottom")
#+END_SRC
There is a significant discrepancy between the data tabulated in the
supplementary materials document and the data plotted on their figure
1: no data points lie above the 400 pCO_{2} mark, while the
spreadsheet data does contain significantly higher values. Note also
the anomalous calculation of pCO_{2} from the Boron values from the
Seki data: from boron values of around 18 (with only one single data
point in the de la Vega data set falling to such a low value) arriving
at pCO_{2} concentrations on a par with boron values of 19.5 in the
Martinez-Boti and de la Vega data cannot be justified.

It seems like a good idea to go back to the original publications and
try to obtain the data from there.

So, let's turn to the \citet{martinez-boti-al15:sensitivity}
directly. Fortunately, the supplementary materials of the article
contains a spreadsheet with data of interest.
#+BEGIN_SRC R :file output/martinez_supp.pdf
  martinez_sm <- read.delim("data/martinez2015_boron.dat", skip = 5)

  ggplot(martinez_sm) +
      geom_point(aes(Age, Boron, colour = Site)) +
      geom_line(aes(Age, Boron, colour = Site)) +
      labs(title = "Martinez-Boti Boron offsets in Pliocene Foraminifera",
           x = "Time (kY)",
           y = expression(paste(delta ^{11}, 'B'))) +
      theme(legend.position = "bottom")
#+END_SRC

And, after calculations (and assumptions!) by the authors, estimates
of CO_{2}
#+BEGIN_SRC R :file output/martinez_supp_co2.pdf
  ggplot(martinez_sm) +
      geom_pointrange(aes(Age, pCO2, ymin=pCO2cil, ymax=pCO2ciu, colour = Site)) +
      geom_line(aes(Age, pCO2, colour = Site)) +
      labs(title = "Martinez-Boti CO2 from Boron in Pliocene Foraminifera",
           x = "Time (kY)",
           y = "pCO2") +
      theme(legend.position = "bottom")
#+END_SRC
Clearly, the originally published data do show pCO_{2} values well in
excess of the 400 mark, quite a few reaching 450. So much for the
\citet{delavega-al20:piacenzian} publication.

A separate study by \citet{dyez-al18:variability} likewise contains a
lot of Boron data.
#+BEGIN_SRC R :file output/dyez_boron.pdf
  dyez_boron <- read.delim("data/dyez2018.dat", skip = 4)

  ggplot(dyez_boron) +
      geom_point(aes(Age, Boron, colour = Site)) +
      geom_line(aes(Age, Boron, colour = Site)) +
      labs(title = "Boron offsets by Dyez et al., 2018",
           x = "Time (kY)",
           y = expression(paste(delta ^{11}, 'B'))) +
      theme(legend.position = "bottom")
#+END_SRC

Using a set of assumptions, these lead to the following proposed
atmospheric CO_{2} concentrations.
#+BEGIN_SRC R :file output/dyez_co2.pdf
  ggplot(dyez_boron) +
      geom_point(aes(Age, co2_atmosphere, colour = Site)) +
      geom_line(aes(Age, co2_atmosphere, colour = Site)) +
      labs(title = "Atmospheric CO2 by Dyez et al., 2018",
           x = "Time (kY)",
           y = expression(paste(mu, 'atm'))) +
      theme(legend.position = "bottom")

#+END_SRC

The time has come to take a careful, critical, look at the nature of
the link between boron and CO_{2}.

* Epilogue

** An aside on the possible use of Catastropy Theory
There are indications that CO_{2} levels have to drop below 300-350
ppm, before glacial-interglacial alternations kick off
\citep{canadell-al21:IPCC6-biogeochemical,delavega-al20:piacenzian}. If
the inferred concentrations of CO_{2} can be made robust (which is an
open question for now, in view of my reservations re the way in which
Boron is used as a proxy), this would be a very good indication that
the approach taken by catastrophe theory may be useful.

The scenario would run along these lines. As long as CO_{2}
concentrations remain high enough, the greenhouse effect is
sufficiently large to mitigate the astronomical insolation variation
and maintain a hothouse Earth. As CO_{2} continues to be sequestered
over geological time, a point is reached where the greenhouse effect
can no longer sustain a permanent hothouse Earth, and the
glacial-interglacial alternations become established. Then we need
some quirck in the system so that an interglacial remains locked in
(i.e., the stable last interglacial). The massive injection of CO_{2}
of the Anthropocene to concentrations encountered well before the
glacial-interglacial alternations would then kick the entire system
back to a hothouse Earth (after the various biogeochemical cycles have
adjusted to a new equilibrium).

The energy input into the Earth system is astronomically determined
(control 1). The atmospheric CO_{2} concentration determines (to a
large extent, but how large?) the amount of heat captured from the
insolation (control 2). The (average) Earth temperature is a
consequence of the captured heat (behaviour). 

Of course, there are important complications. The atmospheric CO_{2}
is the result of a partitioning between atmosphere and hydrosphere
(the latter temperature dependent). And then there are the various
sequestration processes.

Something similar governs the heat budget as well. The hydrosphere can
store substantial amounts of heat, but this will influence the
redistribution patterns of the oceans. (Another thought: epeiric
basins have all but disappeared, compared to earlier geological
times. That must have a significant(?) influence of the CO_{2} storage
capacity of the oceans; large expanses of water will be warmer, and
store less CO_{2}, possibly/likely draining part of the deep storage
as a result).


\citet{thom72:stabilite}

For any system that seeks to minimize a function, only seven different
local forms of catastrophe ``typically'' occur for four or fewer
variables:

1. Fold catastrophe,
2. Cusp catastrophe,
3. Swallowtail catastrophe,
4. Butterfly catastrophe,
5. Elliptic umbilic catastrophe,
6. Hyperbolic umbilic catastrophe, and
7. Parabolic umbilic catastrophe.

More specifically, for any system with fewer than five control factors
and fewer than three behavior axes, these are the only seven
catastrophes possible. The following tables gives the possible
catastrophes as a function of control factors and behavior axes.

| controls | 1 behaviour | 2 behaviour                          |
|----------+-------------+--------------------------------------|
|        1 | fold        |                                      |
|        2 | cusp        |                                      |
|        3 | swallowtail | hyperbolic umbilic, elliptic umbilic |
|        4 | butterfly   | parabolic umbilic                    |

The following table gives prototypical examples for equations showing each type of catastrophe.
| equation                      | catastrophe                                    |
|-------------------------------+------------------------------------------------|
| $x^3+ux$                      | fold catastrophe                               |
| $x^4+ux^2+vx$                 | cusp catastrophe, Riemann-Hugoniot catastrophe |
| $x^5+ux^3+vx^2+wx$            | swallowtail catastrophe                        |
| $x^3+y^3+uxy+vx+wy$           | hyperbolic umbilic catastrophe                 |
| $x^3/3-xy^2+u(x^2+y^2)+vx+wy$ | elliptic umbilic catastrophe                   |
| $x^6+ux^4+vx^3+wx^2+tx$       | butterfly catastrophe                          |
| $x^2y+y^4+ux^2+vy^2+wx+ty$    | parabolic umbilic catastrophe                  |

* References

\bibliographystyle{plainnat}
\bibliography{climate}

